### ISSUE TITLE
Unable to find step, implemented with new line between '(' and '/^'

### ISSUE THREAD

**Issue by avdynut** [alexkrechik/VSCucumberAutoComplete#107]
Step not found, example
```
  this.When(
        /^I set..
```
In this cases all works:
`this.When(/^I set..`
`this.When(   /^I set..`

**Comment by AlexKTest** [comment]
Hi! Are you sure, that you would like to use the newline after this.When( ?

**Comment by alexkrechik** [comment]
Hi! Are you sure, that you would like to use the newline after this.When( ?

**Comment by avdynut** [comment]
You're right. We can delete newlines in our project.
Thanks

**Comment by alexkrechik** [comment]
You are welcome.
