### ISSUE TITLE
Add support of different spoken language

### ISSUE THREAD

**Issue by Aracturat** [alexkrechik/VSCucumberAutoComplete#122]
We can write scenarios in different spoken languages. (https://github.com/cucumber/cucumber/wiki/Spoken-languages )

Is it possible to highlight keywords of other languages (for example, Russian)?

**Comment by alexkrechik** [comment]
Hi! Looks like, Russian language keywords are not present [here](https://github.com/alexkrechik/VSCucumberAutoComplete/blob/master/gclient/syntaxes/feature.tmLanguage)
You can add [these](https://github.com/cucumber/cucumber/blob/master/gherkin/gherkin-languages.json#L2372) russian keywords to tmLanguage (I'll review your merge request), or I'll do this by myself when I'll have free time (probably this weekend)

**Comment by Aracturat** [comment]
Does your extension look at `# language: xx` header at feature file to understand current feature language or does it always highlight all keywords in tmLanguage file?

**Comment by alexkrechik** [comment]
It is always hoghlight all the words found in tmLanguage file.

**Comment by Aracturat** [comment]
Is it possible to look at this header?

**Comment by JesseZomer** [comment]
I also would like support for different spoken languages. If our .feature files don't use the English words 'Given, Then, When' etc the whole extension doesn't work.

**Comment by alexkrechik** [comment]
Highlighting should properly work for all the gherkin words from tmLangiage file, but some rework required to suport all the server features (like autocompletion) for non-English words

**Comment by JesseZomer** [comment]
The highlighting does indeed work. However I'm mostly interested in the 'go-to-definition' and autocompletion features.

**Comment by alexkrechik** [comment]
Go to definition and steps checking was added for the many languiages in 2-5-0

**Comment by leemuar** [comment]
Tried russian:

no autocompletion for russian keywords at all

highlighting does not work for some keywords: 
* также (and)
* иначе (but)
* примеры (examples)
* функция (feature)
* функциональность (feature)
* Свойство (feature)
* Дано (given)
* Пусть (given)
* когда (when)
* тогда (then)
* Затем (then)

![image](https://user-images.githubusercontent.com/5869791/38871784-6ed5a58a-425a-11e8-93a3-ae2a7be39a60.png)
