### ISSUE TITLE
Specflow Integration

### ISSUE THREAD

**Issue by Priyank-Agrawal** [alexkrechik/VSCucumberAutoComplete#123]
Is this extension compatible with specflow feature files?

**Comment by alexkrechik** [comment]
Could you please provide an example of specflow feature file.

**Comment by puco** [comment]
I think the Specflow feature file is a normal Gherkin feature file. I assume the integration would be about getting steps from Specflow step definition files (usually C#).

**Comment by alexkrechik** [comment]
Please reopen the issue if valid  with specflow feature file example / specflow step definitions file or with error getting during extension use. Thank you.
