### ISSUE TITLE
Cucumber 2 support

### ISSUE THREAD

**Issue by kevin-bruton** [alexkrechik/VSCucumberAutoComplete#124]
Looks like step definitions are not recognized when they are written as Cucumber Expressions instead of Regular Expressions. Since the Cucumber documentation now seems to favor Cucumber Expressions, it maybe important to support them.
Cf. [https://docs.cucumber.io/cucumber-expressions/](https://docs.cucumber.io/cucumber-expressions/)

**Comment by alexkrechik** [comment]
Hey! Looks like I've added such functionality in https://github.com/alexkrechik/VSCucumberAutoComplete/issues/66 scope [here](https://github.com/alexkrechik/VSCucumberAutoComplete/blob/master/gserver/src/steps.handler.ts#L132)

**Comment by kevin-bruton** [comment]
Maybe mine is another issue then. The problem started after updating to Cucumber 2.
Now we're writing our step definitions like this:

```
const { defineStep } = require('cucumber');
const conditionsPage = require(
  '../page_objects/conditions-page');

defineStep('check conditions are shown to the user', async function () {
  await conditionsPage.checkConditionsShown();
});

```
Any idea why the step in the feature file can't find the step definition described above?

**Comment by alexkrechik** [comment]
The problem is related to the new steps defining format. Plugin doesn't know that `defineStep('check conditions are shown to the user', async function () {` is cucumber string&

**Comment by alexkrechik** [comment]
Is there any cucumber2 plugin specification with describing of all the steps definition formats supported for different programming languages (like https://cucumber.io/docs/reference)?

**Comment by kevin-bruton** [comment]
According to the documentation, it looks like defineStep has three aliases: Given, When, Then
cf. [https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/api_reference.md#definesteppattern-options-fn](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/api_reference.md#definesteppattern-options-fn)

I've tried adding defineStep [here](https://github.com/alexkrechik/VSCucumberAutoComplete/blob/master/gserver/src/steps.handler.ts#L98) at it seems to work!

Thanks for pointing me in the right direction.

**Comment by alexkrechik** [comment]
Added to 2-4-0.
