### ISSUE TITLE
Steps autocomplete is not contextual

### ISSUE THREAD

**Issue by znevrly** [alexkrechik/VSCucumberAutoComplete#128]
Given steps defined
When the autocomplete is invoked after Gherkin statement keyword

**Expected behaviour**
Only steps are available

**Actual behavior**
Gherkin keywords are available even when there is no sense. Eg. after writing "When" all keywords are available. See the picture.

![vs_code_cucumber](https://user-images.githubusercontent.com/1698263/31578398-b8fbb530-b120-11e7-8567-5668c3b30dec.png)

P.S Great work with this plugin. Thx.

**Comment by alexkrechik** [comment]
Unfortunately, there are no ability to control non-gherkin suggestions from the extension side (I can provide only list of suggestions I would like to provide and vscode doing all the other things). In your case "editor.snippetSuggestions" vscode option change could help you - see https://github.com/Microsoft/vscode/issues/9286
