### ISSUE TITLE
No step definition found for "..."

### ISSUE THREAD

**Issue by DewaldSchoonderwoerd** [alexkrechik/VSCucumberAutoComplete#130]
Hi, the go to function does not work. Maybe I am doing something wrong but when I right click on a step and select the Go to Definition option, I get this error No step definition found for "...".

settings.json:
{
        "cucumberautocomplete.steps": [
            "features/step_definitions/**/*.rb",
            "features/step_definitions/*.rb"
        ],
        "cucumberautocomplete.syncfeatures": "features/*feature"
}

I do have a features folder and step_definitions folder

**Comment by alexkrechik** [comment]
Could you try to use next steps variable?
[
"features/step_definitions/**/*.rb"
]

Anyway, wrong steps pathes (that correlate with no files) should be marked with warning in the 'vscode/settings.json' file

**Comment by DewaldSchoonderwoerd** [comment]
Hi, @alexkrechik thanks for the reply.
I have added the full path now.

{
    "cucumberautocomplete.steps": [
        "../features/step_definitions/**/*.rb",
        "../features/step_definitions/*.rb"

    ],
    "cucumberautocomplete.syncfeatures": "features/*.feature"
}

I do get an error now: "No steps files found"
I do have steps files in the step_definitions directory

**Comment by alexkrechik** [comment]
Could you please provide full pathye to the steps ? 
Anyway, you should find glob path to your files, If you are getting "No steps files found" - path to the files is wrong.

**Comment by alexkrechik** [comment]
Please reopen issue if valid with full path to the any step file
