### ISSUE TITLE
Go to Definition in another language

### ISSUE THREAD

**Issue by mauroscl** [alexkrechik/VSCucumberAutoComplete#132]
I would like to write my features in pt language. When I do this, "Go to definition" doesn't work. That funcionality works fine when I write the steps in English.
This works:
Given que insiro o texto "usuario@email.com" no campo Usuário
This doesn't works:
Dado que insiro o texto "usuario@email.com" no campo Usuário
I need some type of configuration to get pt language working or it is not supported?
Thanks!!!

**Comment by alexkrechik** [comment]
Unfortunately, this is not supported for now. Some extension rework is required for this due to all the extensions functions should be supported for all the languages (like formatting and highlighting)

**Comment by alexkrechik** [comment]
Should be looks good in 2-5-0
