### ISSUE TITLE
Issue with cucumberautocomplete

### ISSUE THREAD

**Issue by dm4rco** [alexkrechik/VSCucumberAutoComplete#133]
I'm facing a weird issue when using the VSCucumberAutoComplete feature.
When writing a step in my feature file the autocomplete suggests me the correct steps but when choosing the step I get the message
`[cucumberautocomplete] Was unable to find step for "Given I am on screen xy"`

I'm using: 
`Visual Studio Code 1.18.1`
`Cucumber (Gherkin) Full Support 2.4.1`
`Cucumber 2.4.0`
`Ruby 2.4.0p0`

**Comment by alexkrechik** [comment]
Could you please provide the step definition for this step ?

**Comment by alexkrechik** [comment]
Please reopen the issue with definition of "Given I am on screen xy" step if issue still be valid.
