### ISSUE TITLE
Unable to format feature file that ends with a data table

### ISSUE THREAD

**Issue by bcklo** [alexkrechik/VSCucumberAutoComplete#147]
The following error message is displayed in the Cucumber auto complete plugin output when the last line of the file is a data table. Adding an empty line solves this issue but would be nice to get fixed.

[Error - 2:20:05 PM] Request textDocument/formatting failed.
  Message: Request textDocument/formatting failed with message: Cannot read property 'search' of undefined
  Code: -32603

**Comment by alexkrechik** [comment]
Fixed in 2.6.0
