### ISSUE TITLE
Cannot read property 'getDefinition' when holding down Ctrl

### ISSUE THREAD

**Issue by bcklo** [alexkrechik/VSCucumberAutoComplete#148]
Holding down Ctrl and moving the mouse over any text produces the following error:

[Error - 2:24:06 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'getDefinition' of undefined
  Code: -32603 

Seems like this may be triggered by the peek definition functionality when cucumberautocomplete.steps is not setup.  We have business analysts and QAs writting gherkin only and so they won't have steps/pages configured.  This can occur quite frequently while trying to do ctrl c/v/z etc. and the cursor happens to be over a word so it can get a bit annoying.

**Comment by thomthom** [comment]
I'm also getting the same error message - it pops open the terminal window in Code.

```
[Error - 19:28:44] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'getDefinition' of undefined
  Code: -32603 
```

**Comment by alexkrechik** [comment]
Should be looks good in 2.6.0
