### ISSUE TITLE
Regex like "(?:Abort|Cancel)" throws error

### ISSUE THREAD

**Issue by Planktom** [alexkrechik/VSCucumberAutoComplete#150]
With the update to the latest version of the extension (2.5.0), I get an error like:
`[Error - 10:25:52] Notification handler 'workspace/didChangeConfiguration' failed with message: Invalid regular expression: /^?:Abort execution of "([^"]*)"$/: Nothing to repeat`

for the step:
`^(?:Abort|Cancel) execution of "([^"]*)"$`

This leads to no suggestions at all.
This was working before the update.

Seems to be brought into with the change/improvement:
`Steps, which contains some 'or' parts (like I do (something|another thing)) will be showed as several different steps`

**Comment by alexkrechik** [comment]
Should be looks good in 2.6.0 - two different steps should appear for such string

**Comment by adamzolotarev** [comment]
I'm still getting an error in 2.6.0 for this expression: ` (1st|2nd|\d+(?:st|nd|rd|th))`
The error is
`Notification handler 'workspace/didChangeConfiguration' failed with message: Invalid regular expression: /^Time Left for 1st) should be (.*)$/: Unmatched ')'`

**Comment by alexkrechik** [comment]
Looks like, that issue is related to the second level of braces and its looks good for regex like '(?:st|nd|rd|th)'. Could you please create separate issue for this?

**Comment by adamzolotarev** [comment]
yep, will do. Thanks!

**Comment by bencatjakub** [comment]
I don't believe anything was fixed. Still have the same issue.

New issue is here #156
