### ISSUE TITLE
Not Format for Doc Strings Step Arguments

### ISSUE THREAD

**Issue by edgarjrg** [alexkrechik/VSCucumberAutoComplete#153]
i have a Step like: 

```
When I query with variables:
      """"
      {
          "id": 1,
          "skills" : [ {
             "name": "mage"
            }]
      }
      """
```
When i format the code it becomes :

```
When I query with variables:
      """"
      {
      "id": 1,
      "skills" : [ {
      "name": "mage"
      }]
      }
      """
```
and i lose readability, is there a way to turn off the format for the Doc Strings ?

**Comment by logavanc** [comment]
It would be even better to just pass off formatting and syntax highlighting to the contained doc-string type (see https://relishapp.com/cucumber/cucumber/docs/gherkin/doc-strings and the referenced type string annotation):

```gherkin
When I query with variables:
      """"json
      {
          "id": 1,
          "skills" : [ {
             "name": "mage"
            }]
      }
      """
```

**Comment by alexkrechik** [comment]
Realized with cucucumberautocomplete.skipDocStringsFormat option
