### ISSUE TITLE
Multi language support (Portuguese) doesn't work.

### ISSUE THREAD

**Issue by AllanMedeiros** [alexkrechik/VSCucumberAutoComplete#155]
Alex, I've found in 2.6 version why the is not navigating from feature to step definitions: my code is written in Portuguese and the plugin seems to not support it.
I've found another issue where this feature was added, but I tested writing a step in English and then F12 worked just fine.
From the screenshot, the selected line works, but the others don't.
![captura de tela 2017-12-26 as 14 19 23](https://user-images.githubusercontent.com/34678196/34360586-298a2eb0-ea49-11e7-8618-63eb71d8f3db.png)

**Comment by alexkrechik** [comment]
Looks like I need additional info due to Portugese strings are looks good for me:
<img width="223" alt="screen shot 2017-12-26 at 6 08 53 pm" src="https://user-images.githubusercontent.com/5772406/34361160-095cb22e-ea68-11e7-9fbc-3cc5b3092b95.png">

**Comment by AllanMedeiros** [comment]
The keywords in features files in Portuguese works, but you need to leave the matching keywords in step definitions in English (Dado = Given, Quando = When, etc).
My code is in Portuguese on both feature files and step definitions.

**Comment by alexkrechik** [comment]
Reproduced. Will fix this issue in some nearest release.

**Comment by AllanMedeiros** [comment]
Thank you!

**Comment by alexkrechik** [comment]
Should be looks good in 2.6.1 - please retest

**Comment by AllanMedeiros** [comment]
2.6.1 seems to be broken, hitting F12 does nothing, not even errors in output.

**Comment by alexkrechik** [comment]
Looks good using `Dado` word for me. Could you please provide:
1) step definition string you are using
2) gherking string with error from feature file
So I'll test you case and reopen issu if reproduce.

**Comment by AllanMedeiros** [comment]
Hi, I've updated to 2.7 version but noticed the output error below after starting VS Code:
[Error - 15:15:32] Notification handler 'workspace/didChangeConfiguration' failed with message: Invalid regular expression: /pagamentos\/: \ at end of pattern

Settings was the same as before when it was working.
Now even if I change the keywords to English, it doesn't work.

Thanks.

**Comment by AllanMedeiros** [comment]
I have more then 700 hits for word "pagamentos" on my code in almost 50 files.
If it's just one causing the issue, would be some easier way to find it?

**Comment by alexkrechik** [comment]
Looks like that only extension debug could help

**Comment by AllanMedeiros** [comment]
But that error is not on runtime, it's displayed right after opening VS Code, so Ruby Debug plugin can't help.

**Comment by AllanMedeiros** [comment]
![captura de tela 2018-01-15 as 16 50 26](https://user-images.githubusercontent.com/34678196/34957342-5f955cb6-fa14-11e7-93a0-c0f50a065a89.png)

Maybe this more detailed output could help...

**Comment by alexkrechik** [comment]
I ment https://code.visualstudio.com/docs/extensions/debugging-extensions#_running-and-debugging-your-extension.
If you will be unable to find error step - only fix of https://github.com/alexkrechik/VSCucumberAutoComplete/issues/161 will help you.
