### ISSUE TITLE
Invalid regular expression for second level of braces

### ISSUE THREAD

**Issue by adamzolotarev** [alexkrechik/VSCucumberAutoComplete#156]
Getting an error in 2.6.0 for this expression:
When(/^(Option A|Option B) for (1st|2nd|\d+(?:st|nd|rd|th)) should be (.*)$/)...

The error is
Notification handler 'workspace/didChangeConfiguration' failed with message: Invalid regular expression: /^Option A for 1st) should be (.*)$/: Unmatched ')'

Possibly related closed issue: https://github.com/alexkrechik/VSCucumberAutoComplete/issues/150

**Comment by bencatjakub** [comment]
Same here, can't use this plugin anymore, it's slowing me down. Fix this ASAP please!

My error is:
`Notification handler 'workspace/didChangeConfiguration' failed with message: Invalid regular expression: /^(^user|$)( |$)(clicks|$)( |$)(on|$)( |$)(remove|$)( |$)(tags|$)( |$)(?|$)( |$)("(.*?)"|$)( |$)(on|$)( |$)(conversation|$)( |$)("(.*?)"$|$)/: Invalid group`

**Comment by honzakubis** [comment]
same problem here, after 2.6.0 update was installed

**Comment by alexkrechik** [comment]
Should be looks good in 2.6.1 - please retest

**Comment by bencatjakub** [comment]
Why did you close it?

It's not fixed at all. Still present in 2.6.1.!!!

**Comment by lsantos10** [comment]
I also have problems when having second braces on 2.6.1

**Comment by honzakubis** [comment]
still not working in 2.6.1 for me.

Can you revert it back to version before 2.6.0 as hot fix? this bug is blocker for my work

**Comment by alexkrechik** [comment]
Basic case is looks good for me (please look at the extension tests). Please provide failed steps strings examples to allow me to fix all the cases.
Also, I’ll do some hotfix, that will make invariants feature optional.

**Comment by honzakubis** [comment]
my error output:

`[Error - 16:21:34] Notification handler 'workspace/didChangeConfiguration' failed with message: Invalid regular expression: /^(^user|$)( |$)(clicks|$)( |$)(on|$)( |$)(remove|$)( |$)(tags|$)( |$)(?|$)( |$)("(.*?)"|$)( |$)(on|$)( |$)(conversation|$)( |$)("(.*?)"$|$)/: Invalid group`

**Comment by jimishshah** [comment]
my error output: 
```
[Error - 13:26:01] Notification handler 'workspace/didChangeConfiguration' failed with message: Invalid regular expression: /^(^the|$)( |$)((.+)|$)( |$)(of|$)( |$)(the|$)( |$)(top|$)( |$)(?(.*)|$)( |$)(should|$)( |$)(read|$)( |$)("(.*)"$|$)/: Invalid group
```

for the code below
```
Then(/^the (.+) (?:of|in) the (top |first |last )?(.*) should (?:read|be) "(.*)"$/, function() {
});
```

**Comment by jimishshah** [comment]
I fixed my issue by installing the older version. 
- Uninstall the extension completely
 - settings > "extensions.autoUpdate" : false,
- older version of extension at https://alexkrechik.gallery.vsassets.io/_apis/public/gallery/publisher/alexkrechik/extension/cucumberautocomplete/2.5.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

 - Follow this instruction to install the extension manually
https://stackoverflow.com/questions/37071388/how-to-install-vscode-extensions-offline

**Comment by bencatjakub** [comment]
@jimishshah this is not a fix, but a workaround. We don't want that. But a nice solution for sure.

**Comment by alexkrechik** [comment]
Should be looks good in 2.7.0.
Tested with `/^the (.+) (?:of|in) the (top |first |last )?(.*) should (?:read|be) "(.*)"$/)` and many other regexp's.

All the steps definitions should be looks good if `cucumberautocomplete.stepsInvariants  === false`
If `cucumberautocomplete.stepsInvariants  === true` some steps autocompletion may fail, but extension should not crash and no output errors should appear.

**Comment by honzakubis** [comment]
Looks good for me after 2.7.0 update

Thanks!

**Comment by bencatjakub** [comment]
Yep, works here as well.

Thanks.

**Comment by alexkrechik** [comment]
Great, thanks.

**Comment by sbuechner** [comment]
Doesn't seem to fix the following problem:

`{
    "cucumberautocomplete.steps": [
        "**/step_definitions/*.rb"
    ],
    "cucumberautocomplete.syncfeatures": true,
    "files.autoSave": "afterDelay"
}`

leads to 
`[Error - 11:26:09] Notification handler 'workspace/didChangeConfiguration' failed with message: Invalid regular expression: /+/: Nothing to repeat`
