### ISSUE TITLE
Autocomplete not detecting steps correctly when using `prettier`

### ISSUE THREAD

**Issue by caweidmann** [alexkrechik/VSCucumberAutoComplete#159]
Hello

Thanks for the awesome plugin and work you're doing on it!

I ran into an issue which only indirectly has to do with this plugin. On the project I am working with we use `prettier` which auto-formats our JS code. And one thing prettier likes doing is putting methods with multiple params onto new lines. So e.g. before we used prettier our step definition would look like the following:
```
this.Given(/^I modify the order$/, { timeout: 10000 }, () => {
  // step code
});
```
Now it looks like this:
```
this.Given(
  /^I modify the order$/,
  { timeout: 10000 },
  () => {
    // step code
  }
);
```
This in turn causes the following error in the feature file:
```
[cucumberautocomplete] Was unable to find step for "And I modify the order"
```
The issue is that the step does exist. I'm wondering if it would be possible to add in support so that the plugin detects steps by looking at the first param that gets passed in?

**Comment by alexkrechik** [comment]
Added two lines definition support in 2.7.0. Please retest

**Comment by caweidmann** [comment]
Awesome, thank you. Have tested and it works.
