### ISSUE TITLE
feature brief and scenario outline brief indentation

### ISSUE THREAD

**Issue by solidrevolution** [alexkrechik/VSCucumberAutoComplete#160]
Currently when auto formatted indentation of the feature brief and scenario outline brief has the indentation of the last block 
<pre> 1: Feature: Some terse yet descriptive text of what is desired
 2: 
 3: no indentation
 5: 
 6:   Scenario: Some determinable business situation
 7:     ...
</pre>

I think it will be much more clear if there is an extra indent. please see the following snippet i got from [cucumber wiki](https://github.com/cucumber/cucumber/wiki/Gherkin)
<pre> 1: Feature: Some terse yet descriptive text of what is desired
 2:   Textual description of the business value of this feature
 3:   Business rules that govern the scope of the feature
 4:   Any additional information that will make the feature easier to understand
 5: 
 6:   Scenario: Some determinable business situation
 7:     ...
</pre>
  
Thanks for the awesome plugin!

**Comment by Xenya0815** [comment]
Yes, that fix would be nice! I have to undo the formatter changes every time manually at the moment, to make the gherkin linter happy.

**Comment by alexkrechik** [comment]
Should be looks good in 2.10.0
