### ISSUE TITLE
[Feature Request] - User Defined Auto-Format spaces/tabs

### ISSUE THREAD

**Issue by tabuckner** [alexkrechik/VSCucumberAutoComplete#164]
## Description
As a user I would like to be able to define the number of spaces for the auto-formatting feature of this VS Extension. See Below for example and criteria:

```
@FullRegression
@IndentFeature

Feature: User Defined indentation of various selectors
  The default should remain unchanged
  The user should be able to adjust the default parameters to suit their needs
  The settings should be specified through a commonly understood structure, such as .json or a .js object.
  The settings should be granular enough to allow for parts of tabs (e.g. spaces)

  @IndentFeatureTest1
  Scenario 1
  Given I am working within a .feature file and I use the auto-format feature 
    And I have not adjusted the settings for this feature
   Then there should be no change in the User's experience

  @IndentFeatureTest2
  Scenario 2
  Given I am within a .feature file and use the auto-format feature
    And I have adjusted the settings
   Then I should see those parameters correctly reflected in my .feature file

  # Not legitimate criteria; example only
  @Ignore
  @IndentFeatureTest2
  Scenario: To demonstrate examples
   When I use <Header 1> at a field
    And a thing happens
   Then expect another field to show <Header 2>

     Examples:
       | Header 1 | Header 2 |
       |  Value 1 |  Value 2 |
       |  Value 3 |  Value 4 |
```

**Comment by tabuckner** [comment]
@alexkrechik Let me know if the formatting on this is annoying. I just wanted to show what I meant as I explained the criteria.

**Comment by alexkrechik** [comment]
Hi!
Actually, next type of formatting is supported by extension - please see [here](https://github.com/alexkrechik/VSCucumberAutoComplete/blob/master/gserver/test/data/after.format.feature).  In the future plans I wanna fix [this issue](https://github.com/alexkrechik/VSCucumberAutoComplete/issues/160) only.

**Comment by alexkrechik** [comment]
Could you please explain - what do you mean under 'define the number of spaces' ?

**Comment by tabuckner** [comment]
Absolutely, thanks for the quick reply. It would be helpful to be able to define the number of white space before a Gherkin Keyword in feature files. 

## Altered example.feature:
```
..@IndentFeatureTest1
..Scenario 1
..Given I am working within a .feature file and I use the auto-format feature 
....And I have not adjusted the settings for this feature
...Then there should be no change in the User's experience
```

## configuration.json Example:
```
...
"indentation" : [
    "on", {
      "Feature": 0,
      "Background": 0,
      "Scenario": 2,
      "Step": 4,
      "Examples": 5,
      "example": 7,
      "given": 2,
      "when": 3,
      "then": 3,
      "and": 4,
      "but": 4
    }
  ],
...
```

## Use Case: 
By defining the number of spaces the user could ensure the auto-format feature of the extension matched another team's IDE's auto-format. Unfortunately, there is not only one way to format gherkin, and having the flexibility to define 

I took a look at the gserver/src/format.ts on a fork and tested decimal values within FormatConf (ln 10 - ln 25), however I clearly had no idea what I was doing and the attempt was a _failure_.

¯\_(ツ)_/¯

**Comment by alexkrechik** [comment]
Custom format could be provided in 2.11.0 with cucucumberautocomplete.formatConfOverride option like:
```
cucucumberautocomplete.formatConfOverride:  {
    'Feature:': 0,
    'Scenario:': 1,
    'Background:': 1,
    'Scenario Outline:': 1,
    'Examples:': 2,
    'Given': 2,
    'When': 2,
    'Then': 2,
    'And': 2,
    'But': 2,
    '\\|': 3,
    '"""': 3,
    '#': 'relative',
    '@': 'relative',
}
```

**Comment by tabuckner** [comment]
@alexkrechik Dude! Thank you so much!!
