### ISSUE TITLE
Improvement: add double qoutes for cucumber expression {string}

### ISSUE THREAD

**Issue by pausk89** [alexkrechik/VSCucumberAutoComplete#167]
Hi, I am using your extension in vscode and it is really usefull, you did a great job!

And it would be nice if the extension automatically add double qoutes in autocomplete results for {string} cucumber expression. For example:

`When('I fill in the component {string} with {string}'`, the autocomplete result is => `When I fill in the component  with `. It should be `When I fill in the component "" with ""`

If we use regexp it works properly and adds automatically the double qoutes for `"([0-9a-zA-Z\s]+)"`, but I am not able to combine regexp with cucumber expressions.

Thank you in advance

**Comment by alexkrechik** [comment]
Should be looks good in 2.8.0

**Comment by pausk89** [comment]
Thank you! It's working properly with 2.8.0 ;)
