### ISSUE TITLE
Add autocomplete for cucumber expression custom parameter types

### ISSUE THREAD

**Issue by pausk89** [alexkrechik/VSCucumberAutoComplete#168]
If it is possible it would be useful to have autocomplete for cucumber expression custom parameter types. Given, we have defined some custom parameter types like 'workObjectState':

`defineParameterType({
  name: 'workObjectState',
  regexp: /all|open|active|inactive|pending|inactive pending|archived|completed|interrupted/,
  transformer: s => parser.capitalize(s)
});`

And a step which use this parameter:

`Given('the state of the work Object is {workObjectState}'`

The cucumber (Gherkin) autocomplete only leave workObjectState parameter in blank. It would be nice if defined regexp values were also provided in the autocomplete results

**Comment by alexkrechik** [comment]
Will be fixed with https://github.com/alexkrechik/VSCucumberAutoComplete/issues/134

**Comment by alexkrechik** [comment]
Should be looks good in 2.8.0 - try something like
```
"cucumberautocomplete.customParameters": [
        {
            "parameter":"{workObjectState}",
            "value":"all|open|active|inactive|pending|inactive pending|archived|completed|interrupted"
        }
    ],
```

**Comment by pausk89** [comment]
Thank you! It's working properly with 2.8.0 :)

**Comment by badeball** [comment]
This only works with very simple parameter definitions that can also be represented using cucumber expressions, IE. strings that get converted to regular expressions. That just happened to be the case for this issue.
