### ISSUE TITLE
Ignore docstrings when searching for steps

### ISSUE THREAD

**Issue by nbppp2** [alexkrechik/VSCucumberAutoComplete#172]
I am unable to find a setting to allow me to ignore strings that appear to be steps but are not. These pseudo-steps should be ignored. Here is an example of some pseudo-steps.

```
Scenario: I am moving in Metropolis
    Given I complete the move service form
    Then I select "Metropolis" as the city I will live in
    And I click "Submit"
    Then I should see an alert with text: 
    """
    I am Batman
    I am in the Justice League
    I work alone
    I am moving to Metropolis
     Because the commute will be easier
    """
```

Ultimately I'm wondering if there is a setting to ignore these pseudo-steps.

**Comment by alexkrechik** [comment]
Should be looks good in 2.10.0 - commented lines will not be validates
