### ISSUE TITLE
Unable to navigate to step definition on vscode 1.21

### ISSUE THREAD

**Issue by suman90** [alexkrechik/VSCucumberAutoComplete#176]
The extension works fine in vscode 1.17.2 for same settings.json and same workspace, but the navigation is not happening on 1.21. This is not listed as a dependency for this extension, so please let me know if there's anything else messing up this feature.

**Comment by alexkrechik** [comment]
Can't reproduce this with `Version 1.21.1 (1.21.1)` vscode version - all the extensions functions are looks good for me.

**Comment by suman90** [comment]
Thanks for the response. Here is an abstracted version of the folder structure on my workspace root, along with the corresponding settings. I should also mention that I'm using cucumber 1.3.3 and so my steps are not in the "Given()" format, they are still using the "this.Given" syntax.

**Workspace folder structure**
```
.vscode
|--- settings.json
.
.
.
test
|--- support
|--- features
|--- |--- app1
|--- |--- |--- feature_suites
|--- |--- |--- |--- <subfolders containing .feature files>
|--- |--- |--- pages
|--- |--- |--- |--- <subfolders containing page objects .js files>
|--- |--- |--- step_definitions
|--- |--- |--- |--- <all step definitions .js files>
|--- |--- app2
|--- |--- <same folder structure as above>
```

**setting.json contents**
```
{
	"cucumberautocomplete.steps": [
		"test/features/app1/step_definitions/*.js",
		"test/features/app2/step_definitions/*.js"
	],
	"cucumberautocomplete.syncfeatures": "test/features/**/*feature",
	"cucumberautocomplete.strictGherkinCompletion": true,
	"editor.quickSuggestions": {
		"comments": false,
		"strings": true,
		"other": true,
	}
}
```

I've also tried variations on the "cucumberautocomplete.syncfeatures" with value set to 
* true
* full path to one specific feature file
* giving "*.feature" instead of "*feature"

Any thoughts?

**Comment by alexkrechik** [comment]
Everything you described is looks good for me. 

Could you please provide some step definition example for debug?

Also, please doublecheck, that there are no warnings in settings.json file regarding wrong file pathes.

**Comment by suman90** [comment]
Found that the issue was with folder permissions on the appdata folder in C: on my office laptop. Could set up fine on my personal laptop. Closing this issue.
