### ISSUE TITLE
gherkinWord `@Step` is not supported.

### ISSUE THREAD

**Issue by derrix060** [alexkrechik/VSCucumberAutoComplete#178]
gherkinWord `@Step` is not supported.

The tag `@Step` is supported by squish. I think that you need to include this in the [gherkinWords](https://github.com/alexkrechik/VSCucumberAutoComplete/blob/master/gserver/src/steps.handler.ts#L41)

Example:
```feature
When I press Esc
...
Then I press Esc
...
```

```python
@Step("I press Esc")
def step(context):
    keyPress("<Esc>")
```

**Comment by derrix060** [comment]
@alexkrechik Do you want help on this one?

**Comment by alexkrechik** [comment]
This issue is not so hard, but i want to include some other small issues to this mini-release. I believe that I'll complete this on this weekend anyway.

**Comment by alexkrechik** [comment]
Should be looks good in 2.10.0
