### ISSUE TITLE
Support godog by adding `Step` to gherkinWords.

### ISSUE THREAD

**Issue by charlysan** [alexkrechik/VSCucumberAutoComplete#179]
[Godog](https://github.com/DATA-DOG/godog) for [Go language](https://golang.org/) can be easily supported by adding `Step` to the Gherkin Word List (`gherkinWords`).

Here is a short screenshot to show that this actually works:

![recording](http://g.recordit.co/TCa6L1dChG.gif)

**Note**: `"cucumberautocomplete.strictGherkinCompletion"` should be set to `false`

**Comment by alexkrechik** [comment]
It would be better to add it [here](https://github.com/alexkrechik/VSCucumberAutoComplete/blob/master/gserver/src/steps.handler.ts#L109) due to Step is not gherkin word, but, anyway, I'll implement this with the nearest mini-release.

**Comment by charlysan** [comment]
That makes sense. 👌

**Comment by alexkrechik** [comment]
Should be looks good in 2.10.0
