### ISSUE TITLE
I have install this extension, but in Project cucumber icon not get displayed with .feature file. 

### ISSUE THREAD

**Issue by priyankazende** [alexkrechik/VSCucumberAutoComplete#180]
I have installed this extension, but in Project cucumber icon not get displayed with .feature file on mac OS in visual studio.
And may be due to that, I am not able to access spec files also.

**Comment by alexkrechik** [comment]
Extension should correctly work on Mac in Visual Studio. Did you enable this extension after install? Are you sure that there are no cucumber-handling extensions installed? Did you reload Visual Studio after extension install?

**Comment by alexkrechik** [comment]
Please leave a comment / reopen issue if its still exists.
