### ISSUE TITLE
Step detection does not match some specflow steps

### ISSUE THREAD

**Issue by gdstirling** [alexkrechik/VSCucumberAutoComplete#185]
Currently not matching steps of specflow format:

        [StepDefinition(@"does not handle step definition type")]   <- Not matched 
        [Given(@"does not handle ""quoted"" text")]   <- Not matched (only handles \" escaping)

**Comment by gdstirling** [comment]
Sorry, was trying to state that the first example matches OK, just the 2nd and 3rd that are not matching - probably a bit confusing so have amended issue. Happy to put a pull request in with the fix :)

**Comment by gdstirling** [comment]
OK. So the following custom parameter fixes  [Given(@"does not handle ""quoted"" text")]   <- Not matched (only handles \" escaping) (substitutes the double quote for escaped quote)

    "cucumberautocomplete.customParameters": [
        {
        "parameter": "\"\"",
        "value": "\\\""
        }
    ],

**Comment by alexkrechik** [comment]
Support of StepDefinition was added in 2-11-0
