### ISSUE TITLE
Cucumber expressions alternative text incorrect parsing

### ISSUE THREAD

**Issue by igormilla** [alexkrechik/VSCucumberAutoComplete#190]
Hi, I was using a plugin for a while, and today while transitioning codebase to cucumber 3.0 with cucumber expressions, I found that plugin cannot find step declaration if alternative text is defined using `/` , but, for some reason, finds them when `|` are used. This is[ opposite to cucumber spec](https://docs.cucumber.io/cucumber/cucumber-expressions/#alternative-text), or how `cucumber` console application parses steps. 

I prepared a test repo:

https://github.com/igormilla/ruby-cucumber-expressions-alternative-text

You can see it in action on this screenshot:
![vscode](https://user-images.githubusercontent.com/622954/40834195-780fea94-6590-11e8-898e-db3b3821d090.png)

**Comment by alexkrechik** [comment]
Hi!
Extension just use strings between quotes as regular expressions to match them with feature files strings. And this works for all the cases I seen before. I believe you can try to change all the '/' symbols to '|' symbol using `cucumberautocomplete.customParameters` paramter. This should fix your problem.

**Comment by igormilla** [comment]
Hey!
Thanks for replying, and giving a possible workaround. I tested your suggestion and it does the job!
I guess plugin has the same code/regex for parsing steps written as "cucumber expressions" or regex, and that's why it catches alternative options via `|` syntax, as that's the way it works in regex.

You can mark this issue as closed, if you don't have full 'cucumber expressions' syntax support in a near future. Once again it does work with `cucumberautocomplete.customParameters` so it's okay for now

**Comment by alexkrechik** [comment]
Great! Lets close this issue for now.
