### ISSUE TITLE
Should have support for aloe, the python 3 gherkin tests framework.

### ISSUE THREAD

**Issue by GalRogozinski** [alexkrechik/VSCucumberAutoComplete#196]
To create Python3 Gherkin tests one will opt for the aloe framework (https://github.com/aloetesting/aloe).
Now in order to create a step in aloe with python3 one will write the following step:
```
@step(r`this is my step (\d+)`)
def my_step(self, number):
...
```

The prefix `r` indicates a raw string so that the `\` character will processed correctly.
The problem is that your plugin almost works. If I will define the step w/o `r`:
```
@step(`this is my step (\d+)`)
def my_step(self, number):
...
```
Then the plugin will know how to process the file correctly!
So if you can change the code so that the `r` will work it will be great!

**Comment by alexkrechik** [comment]
Could be fixed using https://github.com/alexkrechik/VSCucumberAutoComplete/issues/170 way.
