### ISSUE TITLE
Python step start with a parameter is not working.

### ISSUE THREAD

**Issue by babujan** [alexkrechik/VSCucumberAutoComplete#197]
I have a step as follow
```python
@step('{x} is set to {y}')
def step_impl(context, x, y):
   ```
then the feature file with step
```Then SomeParameter is set to 123```

behave pick up the step fine, but autocomplete cannot jump to the definition.

**Comment by alexkrechik** [comment]
The fastest way to fix this is proper use of formatConfOverride option. Example:

```
"cucumberautocomplete.customParameters": [
    {
        "parameter": "{x}",
        "value": ".*"
    },
   {
        "parameter": "{y}",
        "value": ".*"
    }
  ],
```

**Comment by babujan** [comment]
it worked, 

However now I have this massive list of customParameters because the code I am dealing with have numerous different steps written in this format.

Thank you for the fix.

**Comment by alexkrechik** [comment]
In this case You can use something like:

```
"cucumberautocomplete.customParameters": [
    {
        "parameter": "{.*}",
        "value": ".*"
    },
  ],
```

**Comment by babujan** [comment]
that did not work.

**Comment by alexkrechik** [comment]
Could you please provide some examples ?

**Comment by babujan** [comment]
So let say I have another step
``` python
@step('{abc} do some other thing to {y}')
def step_impl(context, abc, y):
```

when I use what you suggested before
``` json
"cucumberautocomplete.customParameters": [
    {
        "parameter": "{x}",
        "value": ".*"
    },
    {
        "parameter": "{abc}",
        "value": ".*"
    }
  ],
```
and it worked.

However when I changed to the other suggestion 
``` json
"cucumberautocomplete.customParameters": [
    {
        "parameter": "{.*}",
        "value": ".*"
    },
  ],
```
This doesn't work.

**Comment by christippett** [comment]
@babujan is right in that the above example doesn't work. Currently parameters aren't interpreted as regular expressions (values are).

The following change to the `handleCustomParameters` function would allow this to work. @alexkrechik would you be open to a pull request for this? I think it'd be useful to allow parameters to be defined as patterns to avoid defining each parameter explicitly. The only potential complication I see is that existing parameters defined in user's settings will need to be updated if they contain special characters. 

```javascript
handleCustomParameters(step: string): string {
    if (!step) return '';
    this.settings.cucumberautocomplete.customParameters.forEach((p: CustomParameter) => {
        const { parameter, value } = p;
        step = step.split(new RegExp(parameter)).join(value);
    });
    return step;
}
```

**Comment by alexkrechik** [comment]
Some additional changes should be applied to get this works (ex. escape all the regex strings). I'll fix this by my own in the nearest release.

**Comment by alexkrechik** [comment]
Actually, RegEx could be provided as parameter to the options object. Example:
```
"cucumberautocomplete.customParameters": [
    {
        "parameter": "/\{.*\}/",
        "value": ".*"
    },
  ],
```
Will update docs with this info in the future release

**Comment by christippett** [comment]
You'll still need to adjust the `handleCustomParameters` function to convert `parameter` to a RegEx. It'll break existing user's settings who have defined a parameter containing special characters (e.g. Javascript `${var}` parameters).

For backwards compatibility, I was thinking you could add a new `parameterPattern` option to the `customParameters` type to allow new settings to be defined as patterns.

**Comment by alexkrechik** [comment]
Looks like, that I've did mistake in the example above.
User can use some RegEx to set some custom parameters:
```
    "cucumberautocomplete.customParameters": [
        {
            "parameter":/\{a.*\}/,
            "value":"a"
        },
    ],
```

Or use just a string:
```
    "cucumberautocomplete.customParameters": [
        {
            "parameter":"${var}",
            "value":"(a|b)"
        }
    ],
```
