### ISSUE TITLE
Formatting does not seem to work when using a language other than english

### ISSUE THREAD

**Issue by remkoboschker** [alexkrechik/VSCucumberAutoComplete#198]

**Comment by alexkrechik** [comment]
Actually, there are no formatting setup for non-english language. But I've added an ability to provide some custom formatting config. You can try it using next extension option (but, of course, via changing English words by the words you need):
```
"cucumberautocomplete.formatConfOverride": {
    'Feature:': 0,
    'Scenario:': 1,
    'Background:': 1,
    'Scenario Outline:': 1,
    'Examples:': 2,
    'Given': 2,
    'When': 2,
    'Then': 2,
    'And': 2,
    'But': 2,
    '\\|': 3,
    '"""': 3,
    '#': 'relative',
    '@': 'relative',
    },
```

**Comment by remkoboschker** [comment]
Aha, I understand that I can change the English words to the ones I need.

Thank you

**Comment by bam** [comment]
But what does 'relative' mean?
e.g. if I have '#someComment' under 'Scenario…', so comment will be indented by 1? 2?
Now I see it formats '#…' strings below 'And' (inside scenario) to 0 indentation on save with your config provided above.

**Comment by alexkrechik** [comment]
> But what does 'relative' mean?
> e.g. if I have '#someComment' under 'Scenario…', so comment will be indented by 1? 2?
> Now I see it formats '#…' strings below 'And' (inside scenario) to 0 indentation on save with your config provided above.

It should inherit next line indents count (if its formatting type is relative to - app will look to the next line until document ends).

**Comment by marc-rutkowski** [comment]
The following config works for french wording if this can help someone...

```
  "cucumberautocomplete.formatConfOverride": {
    "Fonctionnalité:": 0,
    "Scénario": 1,
    "Contexte:": 1,
    "Plan du scénario:": 1,
    "Exemples:": 2,
    "Etant donné": 2,
    "Soit": 2,
    "Quand": 2,
    "Lorsqu": 2,
    "Alors": 2,
    "Et": 2,
    "Mais": 2,
    "#": "relative",
    "@": "relative",
    "\\|": 3,
    "\"\"\"": 3
  },
```
