### ISSUE TITLE
French words and keep autocomplete

### ISSUE THREAD

**Issue by steftanguy** [alexkrechik/VSCucumberAutoComplete#201]
Hi,
I went from this place : [https://marketplace.visualstudio.com/items?itemName=alexkrechik.cucumberautocomplete#qna](url)

I have been asked to list the keywords that I want to translate into French, so here I am :)

The list :

Feature: -> Fonctionnalité:
Scenario: -> Scénario:
Given -> Etant donné
And -> Et
Then -> Alors
When -> Quand
But -> Mais

Thanks a lot

PS : I looked a little in the code, and I found that the keywords seem to be already present, yet the autocompletion works only if I enter the words in English.

file : /gserver/src/steps.handler.ts (line 41)

const gherkinWords = escapeRegExp(`하지만|조건|먼저|만일|만약|단|그리고|그러면|那麼|那么|而且|同時|當|当|前提|假設|假定|假如|但是|但し|並且|并且|もし|ならば|ただし|しかし|かつ|و|متى|لكن|عندما|ثم|بفرض|اذاً|כאשר|וגם|בהינתן|אזי|אז|אבל|Якщо|Унда|То|Припустимощо|Припустимо|Онда|Но|Нехай|Лекин|Когато|Када|Кад|Ктомуже|И|Задато|Задати|Задате|Если|Допустим|Дадено|Ва|Бирок|Аммо|Али|Але|Агар|А|І|Și|És|anrhegediga|Zatati|Zakładając|Zadato|Zadate|Zadano|Zadani|Zadan|Youseknowwhenyousegot|Youseknowlikewhen|Yna|Yaknowhow|Yagotta|Y|Wun|Wtedy|Wheny'all|When|Wenn|WEN|Và|Ve|Und|Un|Thì|Theny'all|Then|Tapi|Tak|Tada|Tad|Så|Stel|Soit|Siis|Si|Quando|Quand|Quan|Pryd|Pokud|Pokiaľ|Però|Pero|Pak|Oraz|Onda|Ond|Oletetaan|Og|Och|Ozaman|Når|När|Niin|Nhưng|N|Mutta|Men|Mas|Maka|Majd|Mais|Maar|Ma|Lorsque|Lorsqu'|Kun|Kuid|Kui|Khi|Keď|Ketika|Když|Kai|Kada|Kad|Jeżeli|Ja|Ir|ICANHAZ|Ha|Givun|Givet|Giveny'all|Given|Gitt|Gegeven|Gegebensei|Fakat|Eğerki|Etantdonné|Et|Então|Entonces|Entao|En|Eeldades|E|Duota|Dun|Donat|Donada|Diyelimki|Dengan|Denyousegotta|De|Dato|Dar|Dann|Dan|Dado|Dacă|Daca|DEN|Când|Cuando|Cho|Cept|Cand|Cal|Buty'all|But|Buh|Biết|Bet|BUT|Atès|Atunci|Atesa|Angenommen|Andy'all|And|Ama|Als|Alors|Allora|Ali|Aleshores|Ale|Akkor|Aber|AN|Ataké|A`);

**Comment by alexkrechik** [comment]
Looks like, that you are using `"cucumberautocomplete.strictGherkinCompletion": true`, so only words, declared by Given word, will be suggested after 'Given' typed. This will not work for all the other words (including French words and other English cucumber words like 'When'). So in your case you should use `"cucumberautocomplete.strictGherkinCompletion": false option` due to, unfortunately, actually there are no matrix between all the speaking languages.
