### ISSUE TITLE
Given/And step definitions

### ISSUE THREAD

**Issue by ardz** [alexkrechik/VSCucumberAutoComplete#204]
Hello,

Does the extension make a distinction between "Given" and "And":

`this.Given(/^I make a cup of tea$/, function (next) {});
this.And(/^I make a cup of tea$/, function (next) {});`

or are you required to do that above? Given/And are interchangeable? is there no "StepDefinition" attribute? (coming from a specflow background here sorry! literally looking through the documentation for the extension I appreciate there may be something I'm missing! many thanks!)

**Comment by alexkrechik** [comment]
Anyway, you should not define several same steps under the different functions due to Cucumber doesn't care regarding specifier word.

**Comment by alexkrechik** [comment]
Please reply/reopen the issue if it still exists
