### ISSUE TITLE
Setting `cucumberautocomplete.syncfeatures` does not provide steps code completion

### ISSUE THREAD

**Issue by ilyapuchka** [alexkrechik/VSCucumberAutoComplete#206]
Description of this setting says "Will get steps using count from glob-style path or from '**/*.feature' if true", so I've set it to `true`, here are my settings:

```
    "cucumberautocomplete.syncfeatures": true,
    "cucumberautocomplete.strictGherkinCompletion": true,
    "editor.quickSuggestions": {
        "comments": false,
        "strings": true,
        "other": true
    }
```

But with that steps code completion does not seem to work. My expectation is that it should use already existing feature files to suggest steps used in those files. Or am I getting it wrong?
I'm only set this setting and not `steps` as my tests are in Swift and this plugin does not seem to support it, though it supports other languages but JS, like Python and Ruby so I suppose it is theoretically possible to add support for other languages too.

**Comment by alexkrechik** [comment]
Actually, `cucumberautocomplete.syncfeatures` option will get all the used steps from features files provided to sort them only. And, anyway, you should provide `cucumberautocomplete.steps` to get it works due to matching should be performed using regular expressions from your steps definitions.

**Comment by alexkrechik** [comment]
Regatding progrsamming languages - all the languages should be supported. Please reply here if it doesn't.

**Comment by ilyapuchka** [comment]
@alexkrechik make sense. 
Regarding Swift support I actually worked after I set steps property and I set `cucumberautocomplete.strictGherkinCompletion` to `false` because framework I use (XCTest--Gherkin) defines steps using `step` function, not `Given`/`When`/`Then` 🎉
