### ISSUE TITLE
Allow '/' in step definitions

### ISSUE THREAD

**Issue by acristu** [alexkrechik/VSCucumberAutoComplete#21]
Thanks for this extension, very cool.

I have some steps with "/" characters, the current behavior is a bit broken. 
For a step like `this.Given(/^bla bla \/ bla bla/...` creating the regex fails because `match[0].replace(/\//g, '')` replaces the slash but leaves a backslash used for escaping. The error causes all the steps in the corresponding file to be lost.

I've added a quick workaround in `getFileSteps` to have all my steps parsed:
```javascript
...
let match = line.match(/\/.*\//);
...
reg: new RegExp(match[0].replace(/^\//, '').replace(/\/$/, '')),
```

**Comment by alexkrechik** [comment]
Thank you for your feedback. Issues appears to be fixed in 1.1.0 version
