### ISSUE TITLE
 'workspace/didChangeConfiguration' failed 

### ISSUE THREAD

**Issue by Jai-Gogineni** [alexkrechik/VSCucumberAutoComplete#211]
- Since New version today[05/09/2019], cannot map cucumber step_definitions
- On console output it's throwing an error
`[Error - 6:14:18 PM] Notification handler 'workspace/didChangeConfiguration' failed with message: Cannot read property '4' of null`

**Comment by alexkrechik** [comment]
I need more info to reproduce this issue. Do you have any Scenario Outlines in your file ?

**Comment by alexkrechik** [comment]
Could you please also provide cucumber part of your configuration file ?

**Comment by Jai-Gogineni** [comment]
Hi Alex, This is my vscode settings
`{
    "cucumberautocomplete.steps": [
        "src/*/step_definitions/*.js",
    ],
    "cucumberautocomplete.syncfeatures": "src/*/features/*feature",
    "cucumberautocomplete.strictGherkinCompletion": true
}
`
This was working fine until the new release made yesterday.
Thanks

**Comment by alexkrechik** [comment]
Some feature or step definition example, that broke everything, will help me to reproduce this issue locally and fix it due to I cant get many info from `Cannot read property '4' of null` error.

**Comment by alexkrechik** [comment]
Looks like, that I've found source of issue. I'll prepare hot fix for this.

**Comment by alexkrechik** [comment]
Please retest using 2.12.1 version of extension

**Comment by Jai-Gogineni** [comment]
Thanks it's all working now @alexkrechik  👍

**Comment by oricadori** [comment]
Thanks @alex!
