### ISSUE TITLE
Autocompletion for python behave

### ISSUE THREAD

**Issue by pitC** [alexkrechik/VSCucumberAutoComplete#213]
I seems that the "quick suggestions" do not work with python behave files.
When typing the step definition, no suggestions are displayed and a warning is produced:
"Was unable to find step for ..."
When step definition is finished and matches actual phrase in step implementation, the string is properly matched - no warning is displayed anymore and the Peek/Go To Definition are working like a charm.

**To Reproduce**
1. Create a *.py file with step implementation and behave annotation
2. Create a feature file
3. Add step definition matching the created step annotation

**Expected behavior**
Autocompletion shall propose matching phrases when typing.

**Cucumberautocomplete part of VSCode settings:**
```
"cucumberautocomplete.steps": [
        "helloworld/steps/*.py",
    ],
    "cucumberautocomplete.syncfeatures": "helloworld/features/*.feature",
    "cucumberautocomplete.strictGherkinCompletion": true,
    "editor.quickSuggestions": {
        "comments": false,
        "strings": true,
        "other": true
    }
```

**Step definition:**
```
@then('I get an error')
def getError():
    pass
```
**Gherkin step line**
```
Then I get an error
```

**Comment by mtkennerly** [comment]
I've noticed the same thing (plugin version 2.12.1). It seems to be related to `cucumberautocomplete.strictGherkinCompletion`, because if you set that to `false`, then it works fine:

![image](https://user-images.githubusercontent.com/4934192/48988598-54c9d500-f0f4-11e8-99e9-06c72d4f4d4d.png)

.vscode/settings.json:
```
{
    "cucumberautocomplete.steps": ["steps/*.py"],
    "cucumberautocomplete.strictGherkinCompletion": false
}
```

steps/all.py:
```
from behave import *

@given("some multiword precondition")
def step_impl(context):
    pass
```

**Comment by alexkrechik** [comment]
Should be supported in 2.13.0
