### ISSUE TITLE
Cucumber autocomplete was unable to find parameter {string} with \" inside string

### ISSUE THREAD

**Issue by christianroll** [alexkrechik/VSCucumberAutoComplete#214]
I can't use cucumberautocomplete keymap when i pass a string like "\"" as parameter, but code still runs.

I get this problem:
Was unable to find step for "Given I update revision 1 from api "SuperTest" with an interceptor from type "OAuth" with body "{\"position\":1,\"status\":\"REFERENCE\",\"idTemp\":179,\"persist\":true,\"isBroken\":false}" with content "{\"grantTypes\":[\"CLIENT_CREDENTIALS\"]}" on flow "FIRST""

**Comment by alexkrechik** [comment]
Could you please provide step definition and step in feature file example ?
