### ISSUE TITLE
multi dialects support

### ISSUE THREAD

**Issue by andrejnov** [alexkrechik/VSCucumberAutoComplete#216]
When entering **keywords for non english languege/dialect** the keywords **don't get colored coded** in the syntax.
  specifically only alternative dialects for **Feature keyword** get color coded,
  other keywords for dialects stay white.

The official dialects for gherkin are defined on https://docs.cucumber.io/gherkin/reference/#spoken-languages.

Would it be possible to include the dialecs into the plugin for color coding?
That would increase usability of this extension for non-english speaking countries. 

If the extension is meant for english speaking world only than this is a feature request instead of a bug/issue.

**Comment by alexkrechik** [comment]
Hello!

Unfortunately, there are no way to easily include all the spoken languages support into the extension.  Many of spoken languages are actually supported - the full list of keywords could be found [here](https://github.com/alexkrechik/VSCucumberAutoComplete/blob/master/gclient/syntaxes/feature.tmLanguage) and [here](https://github.com/alexkrechik/VSCucumberAutoComplete/blob/master/gserver/src/steps.handler.ts#L40).

You can provide list of words to be supported (or just a language if all the words are listed in [link](https://docs.cucumber.io/gherkin/reference/#spoken-languages) you provided) or create merge request with gherkin words updates for server/client parts of extension.

**Comment by alexkrechik** [comment]
Added all the available 'Given/When/Then' foreign words in 2.13.0
