### ISSUE TITLE
Format Document broken

### ISSUE THREAD

**Issue by johnknoop** [alexkrechik/VSCucumberAutoComplete#218]
![gherkin](https://user-images.githubusercontent.com/3394270/47951076-047baf00-df5c-11e8-9cce-17b9e8d52278.gif)

I've tried with different indentation settings (spaces and tabs) and I get the same, weird result regardless.

**Comment by johnknoop** [comment]
Also, the `"cucumberautocomplete.onTypeFormat": true` setting doesn't seem to do anything. I don't get any reformatting when typing.

**Comment by johnknoop** [comment]
It seems to recognize non-english words for coloring though?

**Comment by alexkrechik** [comment]
Coloring and formatting are totally different functions. Most of the languages should be supported by coloring, but, actually, all the non-english words should be provided in format conf override to get it working.

**Comment by johnknoop** [comment]
Thanks!
