### ISSUE TITLE
Autocomplete with {string} parameter injects [^"]+

### ISSUE THREAD

**Issue by cbrevik** [alexkrechik/VSCucumberAutoComplete#220]
**Describe the bug**
Autocomplete on step with `{string}` parameter (non-RegExp) injects the string `[^"]+`

**To Reproduce**
1. Define a step definition in the following format: `I should not see element with id {string}` (i.e. not using a RegExp).
2. Try to autocomplete that step definition in the feature file.
 
**Expected behavior**
The injected string between the quotation marks should be blank.

**Screenshots**
![autocomplete_string_cucumbervscode](https://user-images.githubusercontent.com/4932625/48197458-13949f80-e356-11e8-956b-790f1f1fd421.gif)

**Cucumberautocomplete part of VSCode settings:**
```json
{
    "cucumberautocomplete.steps": ["__features__/step_definitions/*.js"],
    "cucumberautocomplete.syncfeatures": "__features__/*.feature",
    "cucumberautocomplete.strictGherkinCompletion": true,
    "editor.quickSuggestions": {
        "comments": false,
        "strings": true,
        "other": true
    }
}
```

**Step definition:**
```js
const { expectNotVisibleById } = require("./helpers/interactionHelpers")
const { defineSupportCode } = require("cucumber")

defineSupportCode(function({ Then }) {
    Then("I should not see element with id {string}", async elementId => {
        await expectNotVisibleById(elementId)
    })
})
```

**Gherkin step line**
`And I should not see element with id "[^"]+"`

**Comment by znevrly** [comment]
Hi,
any update with this? It's really annoying, imho it relates that CucumerJS uses {string} now instead of regular expression previously.

Thanks.

**Comment by alexkrechik** [comment]
I'll start to create new extension release scope on this week and will include this issue into it.

**Comment by alexkrechik** [comment]
Should be looks good in 2.13.0

**Comment by cbrevik** [comment]
Confirmed that it's fixed now. Thanks for the fix @alexkrechik!
