### ISSUE TITLE
Highlighter not working on feature file

### ISSUE THREAD

**Issue by arjunjh10** [alexkrechik/VSCucumberAutoComplete#221]
**Describe the bug**
I am using your extension for protractor-cucumber-ts with cucumber-tsflow frameworks, but the highlighter is not highlighting the variable values in the feature files.

**To Reproduce**

Consider the following:
Feature: Feature name

   Feature Description

   Scenario: Abcd
   Given I have logged in as first user

 @given(/^I have logged in as (.*) user$/)
    public async loggedIn(username: string) {
       // My implementation
    }

**Expected behavior**
It should have highlighted the word `first` in my feature file

**Screenshots**
Step Definition
![image](https://user-images.githubusercontent.com/7624561/48987254-327e9880-f182-11e8-8e7e-061e2bc8179b.png)

Feature File: 
![image](https://user-images.githubusercontent.com/7624561/48987264-475b2c00-f182-11e8-9bfe-ff8d833bf363.png)

**Comment by alexkrechik** [comment]
Unfortunately, feature contents highlighting works using tmlanguage file as highlight reason only, so, actually, we can provide only some static highlight rules (like strings, gherkin words and scenario/feature names).
