### ISSUE TITLE
{int} parameters are not highlighted

### ISSUE THREAD

**Issue by znevrly** [alexkrechik/VSCucumberAutoComplete#231]
Hi,
have step with {int} parameter
Then('response status is {int}', function (expectedStatusCode) 

And in VS Code is not highlighted
![image](https://user-images.githubusercontent.com/1698263/50166956-5730e080-02e8-11e9-9e69-58847beaa3f8.png)

**Comment by alexkrechik** [comment]
Unfortunately, there are no correlation between step definition and highlight mechanism

**Comment by MoonStorm** [comment]
This needs to be looked at. There is no reason why the regular/cucumber param expressions to simply be ignored like this since the F12 (go to definition) works. Makes all my features files look unreadable.
