### ISSUE TITLE
Add support to single quoted strings for {string}

### ISSUE THREAD

**Issue by fcr--** [alexkrechik/VSCucumberAutoComplete#232]
To be able to use strings quoted with single quotes for the {string} parameters, it would be good to add an option expanding {string} to `'\'[^\']*\''`.

Maybe adding a cucumberautocomplete.singleQuoteString option.

**Comment by alexkrechik** [comment]
Finally decided, that it would be better to use customParameters option here (due to there are so many extensions options and it's better to try to add more of them):

```
"cucumberautocomplete.customParameters": [{
       "parameter": "{string}",
       "value": "'[^']*'"
   }]
```

**Comment by alexkrechik** [comment]
Please reopen issue/write here if suggested way doesn't work to you.
