### ISSUE TITLE
Feature description triggers step warnings

### ISSUE THREAD

**Issue by chrisahardie** [alexkrechik/VSCucumberAutoComplete#234]
**Describe the bug**
When describing the feature as a user story, I will sometimes trigger warnings that a relevant step could not be found, even though such validation shouldn't occur given feature descriptions are not steps.

**To Reproduce**
Add this to a `.feature` file

```
  Feature: Manage vendor services
    In order to offer my services in the app
    As a vendor
    I want manage the services I offer
```

This will trigger a couple warnings:

>Was unable to find step for "In order to offer my services in the app"

>Was unable to find step for "I want manage the services I offer"

**Expected behavior**
Feature descriptions should not trigger warnings.

**Cucumberautocomplete part of VSCode settings:**
```
{
  "cucumberautocomplete.steps": [
      "src/integration-tests/steps/*.js",
  ],
  "cucumberautocomplete.strictGherkinCompletion": true
}
```

**Step definition:**

Note I am using the cucumber-boilerplate steps: https://github.com/webdriverio/cucumber-boilerplate/tree/master/src/steps

**Comment by markcorgan** [comment]
+1

**Comment by alexkrechik** [comment]
Hotfixed in 2.13.1

**Comment by yon-cuadrado** [comment]
Hello

I still have this error. I have included a repository where you can see the issue in the features included in the folder ,/cucumber/features
