### ISSUE TITLE
Go to Definition stops on string `Date('${date}')`

### ISSUE THREAD

**Issue by jiriskacel** [alexkrechik/VSCucumberAutoComplete#237]
This is a problem since extension version 2.13.0 as in to 2.12.1 it works.

**Description**
If there is in any step file the string `Date('${date}')`, the Go to Definition (F12) stops here for some steps.

**To Reproduce**
1. Have a workspace with three step files with:
>`steps.1.ts`
>```
>Given(/first step/, ...);
>```

> `steps.2.ts`
> ```
> `Date('${date}')`;
> ```
> 

> `steps.3.ts`
> ```
> Given(/second step/, ...);
> ```

2. Have a feature file like:
```
Given first step
And second step
```
3. `F12` on the first line will take you to the right definition
4. `F12` on the second line will take you to the Date string in wrong file

**Comment by alexkrechik** [comment]
`"cucumberautocomplete.stepRegExSymbol": "/"` in 2.14.0 version of extension should fix your problem
