### ISSUE TITLE
[cucumberautocomplete] Was unable to find step for "..... any step on a .feature file" using vscode and cucumber with ruby

### ISSUE THREAD

**Issue by cristinabliss** [alexkrechik/VSCucumberAutoComplete#239]
**Describe the bug**
It looks like this extension is not working. I need help perhapsh something is not set up properly...

**To Reproduce**
1. I have installed the extension
2. my project name is in
c:\qa\automation\v3\fetures etc
C:\qa\automation\v3\features\step_definitions
C:\qa\automation\v3\features\support\pages
3. in vscode i open the folder v3
4. my setting.json
{
    "cucumberautocomplete.steps": ["v3/features/step_definitions/*.rb"],

"cucumberautocomplete.pages": {
        "users": "v3/features/support/pages/*.rb"
},
"cucumberautocomplete.onTypeFormat": true,
"cucumberautocomplete.strictGherkinCompletion": true,
"cucumberautocomplete.syncfeatures": "v3/features/*feature",
"cucumberautocomplete.gherkinDefinitionPart": "(Given|When|Then)\\(",
"editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": true
}
}  

I am not confident is correct.
![image](https://user-images.githubusercontent.com/42068045/51186967-d2b28d00-18a8-11e9-9326-7dabcdc07da8.png)

**Expected behavior**
None of the extension feature is working.
Click right on any step in the feature file shows
[cucumberautocomplete] Was unable to find step for "..... any step on a .feature file" using vscode and cucumber with ruby

**Screenshots**
![image](https://user-images.githubusercontent.com/42068045/51186993-df36e580-18a8-11e9-9c55-9d1181bc9b7f.png)

**Comment by alexkrechik** [comment]
Please remove cucumberautocomplete.gherkinDefinitionPart option - it was added for the rare cases of using. If steps will not be detected after this - please provide some step definition example.

**Comment by cristinabliss** [comment]
Thank you!

I found this on stackoverflow and it working with this:


{
"cucumberautocomplete.steps": ["features/step_definitions/*.rb"],

"cucumberautocomplete.syncfeatures": "features/*feature",
"editor.formatOnSave": true,
"editor.quickSuggestions": {
"other": true,
"comments": false,
"strings": true
}
}




it looks like we actually should not specify the root in the path

So is working.

Kind regards,
Cristina Dumitrescu
