### ISSUE TITLE
Settings config file does not consider files on multiple levels

### ISSUE THREAD

**Issue by uandrei** [alexkrechik/VSCucumberAutoComplete#24]
Steps to reproduce:
- split cucumber step definitions in multiple files across multiple folders (i.e. /src/step_definitions/given.js, /src/step_definitions/then/then_feature1/then_feature1.js, /src/step_definitions/when/when_feature1.js)

- in the settings config file i've put the following setting:
{
  "cucumberautocomplete.steps": [
    "src/step_definitions/**/*.js"
  ],
}

Expected outcome: Cucumber Autocomplete module will pick up all the files and I can use the Go to definition in VS Code

Actual outcome: VS Code says that it cannot find steps for the features I've written

**Comment by alexkrechik** [comment]
Will be fixed with #28 implementation

**Comment by alexkrechik** [comment]
Please retest using 2.0.0
