### ISSUE TITLE
[Feature Request] Linting

### ISSUE THREAD

**Issue by andreroggeri** [alexkrechik/VSCucumberAutoComplete#240]
Hi @alexkrechik great extension that you built.

Do you think is feasible to include some linting on top of this extension ?
I saw some great examples on a [Sonar plugin](https://github.com/racodond/sonar-gherkin-plugin), but I feel that this could be checked directly on the IDE.

I could start a PR, but before I would like to know if this belongs here or on a separate extension.

Thanks !

**Comment by alexkrechik** [comment]
Hi!

In theory, we can add some warnings in case of wrong feature files

**Comment by andreroggeri** [comment]
Sure !

I'll give it a try, it will be heavily based on this repo ! 😆

**Comment by DerZyklop** [comment]
Related: gherkin-lint 
https://github.com/vsiakka/gherkin-lint
