### ISSUE TITLE
How to debug the extension and server

### ISSUE THREAD

**Issue by DonJayamanne** [alexkrechik/VSCucumberAutoComplete#245]
Trying to get started with some changes, but unable to debug the server.
I know I can get it working by moving some files around, but would like to avoid that, any suggestions on how you do this?
Else I can submit a PR with some a contributing.md file for others to get started on this extension.

And yes, awesome extension, and thanks.
I'm trying to use this to build some smoke tests for the VS code Python extension.

**Comment by alexkrechik** [comment]
Hey! Looks like that I've used this topic for the extension debugging -  https://code.visualstudio.com/api/extension-guides/debugger-extension

**Comment by DonJayamanne** [comment]
I know about that, but how do you debug this extension of yours. 
I can't debug it without making changes!
Or do you not debug the code?

**Comment by alexkrechik** [comment]
Looks like, that current 'attach' process doesn't work properly and it should be updated. Last time I did code debug it worked, so it wasn't a problem.

**Comment by alexkrechik** [comment]
Closed as non-issue. Please reopen/comment if some additional problem appear - I will try to help you.
