### ISSUE TITLE
Go to step definition is not working

### ISSUE THREAD

**Issue by siva90144** [alexkrechik/VSCucumberAutoComplete#246]
**Describe the bug**
Hi After adding options as described in website go to step definition not working.
 I have added the path and step definition present under stepDefinations folder.
can you help me?

<img width="135" alt="cucumber" src="https://user-images.githubusercontent.com/19613704/52907139-04f93680-3229-11e9-968b-8da9101e4c39.PNG">

Here is my settings.json file
{
    "cucumberautocomplete.steps": [
        "stepDefinations/*.ts",
    ],
    "cucumberautocomplete.syncfeatures": "test/features/*feature",
    "cucumberautocomplete.strictGherkinCompletion": true
}

**Comment by alexkrechik** [comment]
Could you please also provide step definition example and this step string from feature file.

**Comment by siva90144** [comment]
Feature file:

Scenario: Add functionality testing
        Given I will navigate to "Adding" page
        When I add two numbers "5" and "7"
        Then the output displayed should be "12"

Steps class:

 Given('I will navigate to {string} page', async (string)=> {
                     await browser.get('http://juliemr.github.io/protractor-demo/');        
          });

 When('I add two numbers {string} and {string}',  async(val1, val2)=> {
         
         });  


 Then('the output displayed should be {string}', async (string) =>{
          
          })
         });

**Comment by Hbbb** [comment]
## Environment
Extension Version: `2.13.1`
VS Code Version: `1.31.1`


## The Bug
This is broken for me in a slightly different way.

No matter the step I goto definition for, it always brings me to the same step definition. This is for **every step in the whole project**, not specific steps.

Here are some examples of steps that exhibit this behavior. This is a short list, in actuality *every* step I try this with points to the same step definition.
```gherkin
Given I am a logged in "customer"
Then I should see the content "Sort: Calories"
And I wait for the modal to disappear
When I click the link or button to "Cancel"
```

These examples are provided to show that it's not the presence of string interpolation or regex parameters that causes this behavior. Even statically defined step definitions exhibit this behavior.

Here is the step definition it goes to regardless of the step:
```ruby
When(%r{^I visit a daily view for a "([^"]*)" transportation log$}) do |facility|
  ...
end
```

Any ideas on this? I can file a separate issue if that is more helpful.

Thanks!

**Comment by alexkrechik** [comment]
> ## Environment
> Extension Version: `2.13.1`
> VS Code Version: `1.31.1`
> 
> ## The Bug
> This is broken for me in a slightly different way.
> 
> No matter the step I goto definition for, it always brings me to the same step definition. This is for **every step in the whole project**, not specific steps.
> 
> Here are some examples of steps that exhibit this behavior. This is a short list, in actuality _every_ step I try this with points to the same step definition.
> 
> ```
> Given I am a logged in "customer"
> Then I should see the content "Sort: Calories"
> And I wait for the modal to disappear
> When I click the link or button to "Cancel"
> ```
> 
> These examples are provided to show that it's not the presence of string interpolation or regex parameters that causes this behavior. Even statically defined step definitions exhibit this behavior.
> 
> Here is the step definition it goes to regardless of the step:
> 
> ```ruby
> When(%r{^I visit a daily view for a "([^"]*)" transportation log$}) do |facility|
>   ...
> end
> ```
> 
> Any ideas on this? I can file a separate issue if that is more helpful.
> 
> Thanks!

Yes please, separate issue would be better.

**Comment by alexkrechik** [comment]
Hey, is issue still valid for you? I've started to look at it in release-3.14.0 scope, but was unable to reproduce. Such step looks ok for me, so looks like this is some configuration problem.

**Comment by siva90144** [comment]
Hi Alex,

Still facing issue.
Extension Version: 2.13.1
VS Code Version: 1.32.3

is there any error in config  as shown in first post?

**Comment by alexkrechik** [comment]
Could you try to use customParameters option like:

```
"cucumberautocomplete.customParameters": [{
       "parameter": "(%r{",
       "value": "(/"
   },{
    "parameter": "})",
    "value": "/)"
}]

```

**Comment by alexkrechik** [comment]
Please reopen issue if suggestion above doesn't work for your case.
