### ISSUE TITLE
Feature Request: Support for Feature Synonyms 

### ISSUE THREAD

**Issue by DesHorsley** [alexkrechik/VSCucumberAutoComplete#248]
As per: https://github.com/cucumber/cucumber/blob/2a1e5370278fe1c2876dd15907ca86346efc0074/gherkin/gherkin-languages.json#L752-L755

`Ability` and `Business Need` are synonyms for `Feature`, could these keywords be added to the syntax highlighting feature?

[Writing Great Specifications](https://www.manning.com/books/writing-great-specifications) has some great use cases for these synonyms.

**Comment by alexkrechik** [comment]
Should be implemented in 2.14.0
