### ISSUE TITLE
Go to definition does not work

### ISSUE THREAD

**Issue by uandrei** [alexkrechik/VSCucumberAutoComplete#25]
Steps to reproduce:
- create given.js file at path d:\Work\myapp\src\features\step_definitions\given.js
- set in the .vscode/settings.json the following setting:
{
  "cucumberautocomplete.steps": [
    "src\\features\\step_definitions"
  ]
}
- go in a feature file and select Go To Definition (F12) for a given statement

Expected outcome: VS Code will show me the code for that specific statement

Actual outcome: VS Code throws an error ("Unable to open 'given.js': File not found (\\d:\Work\myapp\src\features\step_definitions\given.js'). The path is correct and the file exists in there. VS Code does not underline the given statement with green line, which means it does recognize where the source comes from, but cannot go to the definition.

**Comment by alexkrechik** [comment]
Please retest using 2.0.0
