### ISSUE TITLE
Definitions with int does not get recognized

### ISSUE THREAD

**Issue by imtiazhossain** [alexkrechik/VSCucumberAutoComplete#251]
**Describe the bug**
When you have a definition with int such as:

When I add 1 + 1

with step definition

When('I add {int} + {int}', function(num1, num2) {
return num1+num2;
}

The cucumber step is highlighted as undefined but it still works

**Expected behavior**
The highlight should go away

**Screenshots**
![image](https://user-images.githubusercontent.com/7926510/54231180-646ffc80-44de-11e9-9c1f-d5ba5489bfb2.png)

**Cucumberautocomplete part of VSCode settings:**
```
{
    "cucumberautocomplete.steps": [
        "test/features/step_definitions/*.js",
        "node_modules/qa-lib/src/step_definitions/*.js"
    ],
    "cucumberautocomplete.syncfeatures": "test/features/*feature",
    "cucumberautocomplete.strictGherkinCompletion": true,
}
```

**Comment by alexkrechik** [comment]
Is Cucumber correctly parse your step? In most it using string passed as RegEx and non-backshalsed '+' symbol will not work as expected. `When('I add {int} \+ {int}', function (num1, num2) { }` will works properly.

**Comment by alexkrechik** [comment]
Also, please advice if all of your steps are parsing like regular string (not RegExp)

**Comment by imtiazhossain** [comment]
It looks fine now. Closing
