### ISSUE TITLE
Background steps are wrongly indented if specified with asterisk

### ISSUE THREAD

**Issue by chbndrhnns** [alexkrechik/VSCucumberAutoComplete#252]
**Describe the bug**
Steps can be given using the [star notation](https://relishapp.com/cucumber/cucumber/docs/gherkin/using-star-notation-instead-of-given-when-then).
If such steps are in the Background section, auto format seems to mess with the indentation.

**To Reproduce**
1. Enter the snippet

```
Feature: a
  Background:
    And first
    * second 
```
2. Save
3. It gets reformatted to

```
Feature: a
  Background:
    And first
  * second 
```

The same happens if you omit the `And ` step and just have one asterisk step

**Expected behavior**
Star notation is indented correctly in the `Background` section

**Screenshots**

**Cucumberautocomplete part of VSCode settings:**
default settings

**Step definition:**
If applicable, add example of step definition:
```
When(/^I rename the run to "([^"]*)"$/, (name) =>
  // ... whatever
);
```

**Gherkin step line**
If applicable, add step line from gherkin file
`When I rename the run to "([^"]*)"`

**Comment by alexkrechik** [comment]
Should be implemented in 2.14.0
