### ISSUE TITLE
Goto step definition always takes me to the same definition

### ISSUE THREAD

**Issue by Hbbb** [alexkrechik/VSCucumberAutoComplete#255]
## Environment
Extension Version: `2.13.1`
VS Code Version: `1.31.1`

## The Bug
This is broken for me in a slightly different way.

No matter the step I goto definition for, it always brings me to the same step definition. This is for **every step in the whole project**, not specific steps.

Here are some examples of steps that exhibit this behavior. This is a short list, in actuality *every* step I try this with points to the same step definition.
```gherkin
Given I am a logged in "customer"
Then I should see the content "Sort: Calories"
And I wait for the modal to disappear
When I click the link or button to "Cancel"
```

These examples are provided to show that it's not the presence of string interpolation or regex parameters that causes this behavior. Even statically defined step definitions exhibit this behavior.

Here is the step definition it goes to regardless of the step:
```ruby
When(%r{^I visit a daily view for a "([^"]*)" transportation log$}) do |facility|
  ...
end
```

Any ideas on this? I can file a separate issue if that is more helpful.

Thanks!

**Comment by alexkrechik** [comment]
Hey! This issue appears due to, unfortunately, actually  `(%r{})` step format is not supported by the extension, so `"([^"]*)"` part, that match everything, was recognized as step. You cant try to add next option to avoid this situation:
```
    "cucumberautocomplete.customParameters": [
        {
            "parameter":"(%r{",
            "value":"('"
        },
        {
            "parameter":"})",
            "value":"')"
        }
    ],
```

**Comment by Hbbb** [comment]
That worked! Thank you so much for the help 👍
