### ISSUE TITLE
Formatting lost when a comment is placed inside a data table of scenraio outline

### ISSUE THREAD

**Issue by iamthadiyan** [alexkrechik/VSCucumberAutoComplete#258]
**Describe the bug**
Given below is a scenario outline table in which because of a comment inside data table, the last line is not affecting the formatting of the lines above it.

> 
> Feature: feature
> 
>     Scenario Outline: outline
>         Given Start to type your Given step here
>         When Start to type your When step here
>         Then Start to type your Then step here
>         Examples:
>             | Header 1 | Header 2 | Header 3 |
>             | Value 1  | Value 2  | Value 3  |
>             # comment
>             | Valueadasdasdas 1 | Valueasdasdasd 2 | Valueasdasdas 3 |

**To Reproduce**
1. Copy the above text
2. Select all
3 .Format Document

**Expected behavior**

> Feature: feature
> 
>     Scenario Outline: outline
>         Given Start to type your Given step here
>         When Start to type your When step here
>         Then Start to type your Then step here
>         Examples:
>             | Header 1          | Header 2         | Header 3        |
>             | Value 1           | Value 2          | Value 3         |
>             # comment
>             | Valueadasdasdas 1 | Valueasdasdasd 2 | Valueasdasdas 3 |

PS: I love this plugin, by the way. Excellent work!

**Comment by alexkrechik** [comment]
Should be fixed in 2.14.0
