### ISSUE TITLE
Add support for Cucumber-TSFlow

### ISSUE THREAD

**Issue by yushir** [alexkrechik/VSCucumberAutoComplete#26]
Currently there's only support for plain .js files, but plenty of us are using TypeScript to develop test cases.
In order to realise the full potential of this awesome plugin, it'd be great to have support for cucumber-tsflow (including steps and such).

Here's the link: https://github.com/timjroberts/cucumber-js-tsflow.

**Comment by alexkrechik** [comment]
Will be fixed with #28 implementation

**Comment by alexkrechik** [comment]
Please retest using 2.0.0
