### ISSUE TITLE
Go to step definition jumps to nested steps calling

### ISSUE THREAD

**Issue by wiro34** [alexkrechik/VSCucumberAutoComplete#261]
I'm using cucumber-ruby.

**Describe the bug**

When a step calls another steps with parameters in the `steps` method,
Go to Definition (F12) jumps to this call.

**To Reproduce**

Create files:

- features/example.feature
```gherkin
Feature: demo
  Scenario: demo
    Given Open browser
```

- features/step_definitions/example_steps.rb
```ruby
Given 'A nested step' do |text|
  # Calling another steps with parameter
  steps <<~GHERKIN
    Given "#{text}" is dummy
  GHERKIN
end

Given 'Open browser' do
  puts 'Open browser'
end
```

Open `example.feature` file.
F12 in `Given Open browser` line goes to `    Given "#{text}" is dummy` of step definition.

**Expected behavior**

It should go to step definition `Given 'Open browser'`.

**Cucumberautocomplete part of VSCode settings:**

```
{
  "cucumberautocomplete.steps": ["features/step_definitions/*_steps.rb"],
  "cucumberautocomplete.syncfeatures": "features/*.feature"
}
```

**Workaround**

I configure `cucumberautocomplete.gherkinDefinitionPart` as follows to prevent indent matching

```
{
  ...
  "cucumberautocomplete.gherkinDefinitionPart": "^(Given|When|Then|Step)"
}
```

If `getPartRegExp` in` steps.handler.ts` has `endPart` matcher, it will work well? (e.g. match the brackets or `do` keyword.)

**Comment by alexkrechik** [comment]
Unfortunately, there are no ability to pass steps special symbol (`'` in your case) to the parser. gherkinDefinitionPart could obtain only step part before the brackets, so `Given "#{text}" is dummy` will be defined as 'match everything' step. Anyway, I'll try to fix this in some way in https://github.com/alexkrechik/VSCucumberAutoComplete/issues/237, that was created before.
