### ISSUE TITLE
Support for "word1/word2" Step Definition

### ISSUE THREAD

**Issue by ravichandra068** [alexkrechik/VSCucumberAutoComplete#262]
**Describe the bug**
We have steps that look similar to:

_**I click on link/button/radio in Section A**_

The above steps are not recognized by the plugin. However, the below step definition is recognized:

_**I click on link/button in Section A**_

This kinda shows that if we were to give more than 1 "/", the plugin is unable to map the step to the corresponding step definition

**To Reproduce**
Try creating a step in the Feature file like this:

_**When I click on radio in Section A**_

And the step definition looks like this:

_**I click on link/button/radio in Section A**_

**Expected behavior**
Even with the presence of multiple "/" between words, the plugin should be able to recognize the step definition for the corresponding step

**Screenshots**
N/A

**Cucumberautocomplete part of VSCode settings:**
```
"cucumberautocomplete.steps": [
        "src/_tests_/acceptance/step-definitions/*.js",
        "src/_tests_/acceptance/step-definitions/**/*.js"
    ],
    "cucumberautocomplete.syncfeatures": "src/_tests_/acceptance/features/*.feature"
```

**Step definition:**
If applicable, add example of step definition:
```
When('I click on {string} link/button/radio in {string} section', function (linkText, sectionName) {
//Function Code
});
```

**Gherkin step line**
`When I click on "ABCC" radio in "Bias" section`

**Comment by alexkrechik** [comment]
Should be fixed in 2.14.0
