### ISSUE TITLE
stepDefiniation Snippet

### ISSUE THREAD

**Issue by skAutomation12** [alexkrechik/VSCucumberAutoComplete#263]
How to create stepdefiniations ?

I mean like there is an option to peek the Step Def tied 

Do we have any option that would help in generate step def snippets.

**Comment by alexkrechik** [comment]
Unfortunately, there are no such option and they could be realized only after all the development langusges separation in framework. Original issue is https://github.com/alexkrechik/VSCucumberAutoComplete/issues/48
