### ISSUE TITLE
Add Quick Fix support

### ISSUE THREAD

**Issue by josepmc** [alexkrechik/VSCucumberAutoComplete#27]
In this feature request we would have:
- Ability to create new step implementations (following the installed template, see for instance https://www.npmjs.com/package/cucumber-snippets-tsflow)
- Lint-like correction of the indentation. Ideally with a flag to enable auto-indentation
- Snippet support (currently if we install this one along other gherkin extensions it'll just break)

**Comment by alexkrechik** [comment]
Thank you for your feedback.
I've move 'Snippets' part to the other issue - #29 due to it more easier to realise and I'm planning to do this in the nearest release. 
I'll handle first two points from this request later.

**Comment by alexkrechik** [comment]
Firxt point functional would be fixed in [#48](https://github.com/alexkrechik/VSCucumberAutoComplete/issues/48) was scope.
Created [#100](https://github.com/alexkrechik/VSCucumberAutoComplete/issues/100) regarding second issue.
Closed this issue due to this.
