### ISSUE TITLE
unable to find step for parameterized steps 

### ISSUE THREAD

**Issue by abhinaba1080** [alexkrechik/VSCucumberAutoComplete#276]
Hi,

Please guide me for the below error. I think i need to update something in the settings.json file. Any  leads will be appropriated.

![image](https://user-images.githubusercontent.com/23141842/60388133-c9218800-9aca-11e9-8d3d-5ce33a92e2b4.png)

**Step def file:**

```
 this.When('user enter "$username" and "$password"', async (username: string, password: string) => {
        await loginFunc.setUserName(username);
        await loginFunc.setUserPassword(password);

    });
```

**Settings.json**

```
{
    "cucumberautocomplete.steps": [
        "test/**/*.ts",
        "src/**/*.ts"
    ],
    "cucumberautocomplete.syncfeatures": "test/e2e/features/*.feature",
    "cucumberautocomplete.smartSnippets": true,
    "cucumberautocomplete.stepsInvariants": true,
    "cucumberautocomplete.skipDocStringsFormat": true,
    "cucumberautocomplete.onTypeFormat": true,
    
    "cucumberautocomplete.customParameters": [
        {
            "parameter":"{ab}",
            "value":"(a|b)"
        }
    ],
    "editor.quickSuggestions": {
        "comments": false,
        "strings": true,
        "other": true
    },
    "cucumberautocomplete.gherkinDefinitionPart": "(Given|When|Then|And)\\("
}
```

**Comment by alexkrechik** [comment]
'user enter "$username" and "$password"' is not valid RegEx for your step. You can try to add some custom parameter like:
"cucumberautocomplete.customParameters": [
        {
            "parameter":"/\"\$.*?\"/",
            "value":"\".*\""
        }
    ]
In this case step will be converted to 'user enter ".*" and ".*"' and after this gherkin line provided should be recognized properly.

**Comment by alexkrechik** [comment]
Please reopen the issue if the previous suggestion doesn't work
