### ISSUE TITLE
Cannot find step definition used import function by require(...)

### ISSUE THREAD

**Issue by Zrollan** [alexkrechik/VSCucumberAutoComplete#283]
![image](https://user-images.githubusercontent.com/24754767/61506649-5fcfcd80-aa15-11e9-9eb0-e9c320cbe0ef.png)
![image](https://user-images.githubusercontent.com/24754767/61506675-770ebb00-aa15-11e9-8fb4-aafeef1f15d5.png)

**Comment by Zrollan** [comment]
Sorry, it worked after add a line break.
![image](https://user-images.githubusercontent.com/24754767/61512154-931d5700-aa2b-11e9-8705-a44dfa4c79e1.png)
![image](https://user-images.githubusercontent.com/24754767/61512185-a4666380-aa2b-11e9-88fa-7da5816778d0.png)

**Comment by alexkrechik** [comment]
Is it ok now? Could I close this issue ?

**Comment by Zrollan** [comment]
Yes, it worked after I added a line break. You can close this issue.Thank you.
