### ISSUE TITLE
Format Document is broken when write a step "response body should be valid json"

### ISSUE THREAD

**Issue by ADMehta** [alexkrechik/VSCucumberAutoComplete#284]
When Write a step as "response body should be valid json". the formatting after this statement is broken. it becomes white text.

"response body should be valid jso"  text works okay but json word messes up with format color.
![Screen Shot 2019-07-22 at 11 16 26 AM](https://user-images.githubusercontent.com/12927575/61654861-3790da80-ac72-11e9-9c80-3af4c2fa18d1.png)

**Comment by Fermich11** [comment]
I'm still able to see this issue! :scream:

**Comment by robin-parker** [comment]
It seems to be any step ending with the word **json** that triggers the issue, for example:
![image](https://user-images.githubusercontent.com/4507581/66784724-29e69c00-eed3-11e9-9c42-7bfa25a8440c.png)

**Comment by Fermich11** [comment]
@alexkrechik taking a quick look on the code I think the issue could be on these line:
https://github.com/alexkrechik/VSCucumberAutoComplete/blob/master/gclient/syntaxes/json-embed.json#L8

**Comment by Hemanbaba** [comment]
it's once disappeared, but now it occurs to me again

**Comment by alexkrechik** [comment]
Fixed in 2.15.1
