### ISSUE TITLE
error message: Couldn't start client Cucumber auto complete plugin

### ISSUE THREAD

**Issue by savbran** [alexkrechik/VSCucumberAutoComplete#285]
On latest version of Visual Studio (1.36.1), I installed this plugin and this happens soon after I run Visual Studio Code:
- The main window of vs code appears;

- In low right corner I can see the message: 
```
Couldn't start client Cucumber auto complete plugin
Source: Cucumber (Gherkin) Full Support (Extension)
```

- the output window shows:
```
[Error - 09:18:28] Starting client failed
Error: spawn C:\Users\sbrancaccio\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
	at onErrorNT (internal/child_process.js:407:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by alexkrechik** [comment]
Unfortunately, was unable to reproduce this issue on my PC using lastest VSCode. Could you please try to reinstall extension or run VS Code without it to be sure issue is relation to the extension ?

**Comment by savbran** [comment]
Hi Alex, sorry this was an issue related to my workspace settings. After that I reset the settings, the error disappeared and the plugin works well.
