### ISSUE TITLE
The Extension stops working after VS Code restart

### ISSUE THREAD

**Issue by ArunaBalasubramanian** [alexkrechik/VSCucumberAutoComplete#287]
**Describe the bug**
The extension works perfectly once the configurations are made, however it stops when VS code is restarted forcing the user to un-install & install the extension again.

Please note that after VSCode restart, all the configuration are still pertained on the user settings.json

**To Reproduce**

1.  Behave - 1.2.6
2. VS Code - 1.36.1
3. OS - Windows 8.1

**Expected behavior**
Extension is expected to pick the configurations from settings.json and behave as per the rule

**Screenshots**

**Initial set up:**
![InitialSetup](https://user-images.githubusercontent.com/24669266/61947938-1c043780-afc4-11e9-8191-aa5622220278.JPG)

**After VS restart:**
![AfterVSRestart](https://user-images.githubusercontent.com/24669266/61947944-21618200-afc4-11e9-8a3d-fc1d79857aaa.JPG)

**Cucumberautocomplete part of VSCode settings:**
```
"cucumberautocomplete.steps": ["steps/**/*.py"],
    "cucumberautocomplete.strictGherkinCompletion": false,
    "cucumberautocomplete.syncfeatures": "features/**/*.feature",
    "cucumberautocomplete.gherkinDefinitionPart": "@(given|when|then|step)\\(",
    "cucumberautocomplete.onTypeFormat": true,
    "editor.formatOnType": true,
    "editor.quickSuggestions": {
        "comments": false,
        "strings": true,
        "other": true
    }
```

**Step definition:**
```
@given('I am on "{title}" screen')
def verify_loginpage(context,title):
pass
```

**Gherkin step line**
`Given I am on "Login" screen`

**Comment by alexkrechik** [comment]
Looks like, that issue was related to some delay at the beginning of extension work. Please, advice - is the issue still valid for you?

**Comment by ArunaBalasubramanian** [comment]
Now we have noticed that it works for few of us, but not for others(We work on Win OS 8 or 10)
The extension doesn't seem to pick up the configuration even after indefinite wait time, so I don't think the issue is caused by delay

**Comment by alexkrechik** [comment]
Do you have any issues in Debug Console or Output sections?

**Comment by ArunaBalasubramanian** [comment]
There are no issues listed under console/output sections
