### ISSUE TITLE
No steps files found

### ISSUE THREAD

**Issue by leosfdc** [alexkrechik/VSCucumberAutoComplete#288]
**Describe the bug**

unable to create a .feature file without warning. The settings.json file has a warning for steps and step definitions.

1. Go to : settings.json
2. Add the below json in the settings.json file 
{  
  "salesforcedx-vscode-core.push-or-deploy-on-save.enabled":false,
  "search.exclude":{  
     "**/node_modules":true,
     "**/bower_components":true,
     "**/.sfdx":true
  },
  "cucumberautocomplete.steps":[  
     "test/features/step_definitions/*.js",
     "node_modules/qa-lib/src/step_definitions/*.js"
  ],
  "cucumberautocomplete.syncfeatures":"test/features/*feature",
  "cucumberautocomplete.strictGherkinCompletion":true,
  "cucumberautocomplete.smartSnippets":true,
  "cucumberautocomplete.stepsInvariants":true,
  "cucumberautocomplete.gherkinDefinitionPart": "(Scenario:)",
    "cucumberautocomplete.stepRegExSymbol": ".",
  "eslint.nodePath":"c:\\Users\\user\\.vscode\\extensions\\salesforce.salesforcedx-vscode-lwc-46.7.0\\node_modules"
}
3. click save
4. See warning : 

No steps files found cucu,mberautocomplete [9,6]
No steps files found cucu,mberautocomplete [10,6]

**Expected behavior**
No warning should appear on save
**Screenshots**

**Cucumberautocomplete part of VSCode settings:**
```
{  
  "salesforcedx-vscode-core.push-or-deploy-on-save.enabled":false,
  "search.exclude":{  
     "**/node_modules":true,
     "**/bower_components":true,
     "**/.sfdx":true
  },
  "cucumberautocomplete.steps":[  
     "test/features/step_definitions/*.js",
     "node_modules/qa-lib/src/step_definitions/*.js"
  ],
  "cucumberautocomplete.syncfeatures":"test/features/*feature",
  "cucumberautocomplete.strictGherkinCompletion":true,
  "cucumberautocomplete.smartSnippets":true,
  "cucumberautocomplete.stepsInvariants":true,
  "cucumberautocomplete.gherkinDefinitionPart": "(Scenario:)",
    "cucumberautocomplete.stepRegExSymbol": ".",
  "eslint.nodePath":"c:\\Users\\useri\\.vscode\\extensions\\salesforce.salesforcedx-vscode-lwc-46.7.0\\node_modules"
}
```

**.featurefile**
1 Feature:I want to test Account Creation
2 @Test1
3 Scenario: Open Account Page
4 Given navigate to "https://login.salesforce.com"
5 Given username "" and password ""
6 Then select "/001/o"

**Gherkin step line**
If applicable, add step line from gherkin file
Given navigate to "https://login.salesforce.com" line 4
Given username "" and password "" line 5
Then select "/001/o" line 6

For lines 4,5,6 I get the warning:  'Was unable to find step for'

**Comment by alexkrechik** [comment]
cucumberautocomplete.steps array should consist of valid strings with path to the steps files. Are your steps files are located in `test/features/step_definitions/*.js` or `node_modules/qa-lib/src/step_definitions/.js` (like test/features/step_definitions/steps.js) ?

**Comment by alexkrechik** [comment]
Please reopen issue if warning still exists and some valid steps present under:
```
"test/features/step_definitions/*.js",
"node_modules/qa-lib/src/step_definitions/*.js"
```
