### ISSUE TITLE
Autocomplete does not find step definition that uses RegExp constructor

### ISSUE THREAD

**Issue by ericmacfa** [alexkrechik/VSCucumberAutoComplete#289]
**Describe the bug**
The autocomplete does not recognize a step that uses the `new RegExp()` constructor instead of a regex literal

**To Reproduce**
Please see the step definition and gherkin provided below.

**Expected behavior**
The autocomplete should recognize steps that are defined with the RegExp constructor. 

![image](https://user-images.githubusercontent.com/18381801/62322313-670dc700-b46a-11e9-8ca8-88b74746b44e.png)

Literal regex are clear and concise, but lack any ability to re-use patterns that are shared by multiple steps.

**Screenshots**
The step defined with the RegExp constructor is not recognized.
![image](https://user-images.githubusercontent.com/18381801/62321443-43e21800-b468-11e9-9ec0-ad7275045e55.png)

The step defined with a regex literal is recognized as expected.
![image](https://user-images.githubusercontent.com/18381801/62321516-755ae380-b468-11e9-8b23-f2dd6ce2cfeb.png)

**Cucumberautocomplete part of VSCode settings:**
```
{
    "cucumberautocomplete.steps": ["./test/steps/**/*.steps.js"],
}
```

**Step definition:**
_test/steps/Given.steps.js_
```js
// Given(/^I have navigated to the "([^"]+)" page$/, pageName => {}); // Is recognized
Given(new RegExp('^I have navigated to the "([^"]+)" page$'), pageName => {}); // Is not recognized 
```

**Gherkin step line**
_test/features/example.feature_
```
Feature: Example
    Scenario: Demonstrate the issue
        Given I have navigated to the "Home" page
```
> Given I have navigated to the "Home" page

**Comment by gialletti** [comment]
Also, it'd be great to be able to pass variables to the regular expressions!
```
// This is recognized
When(
  /^I have navigated to the "([^"]+)" page by (mobile|desktop)$/,
  (pageName: string, device: string) => {});

// None of these are recognized
const deviceList = ['mobile', 'desktop'] as const;
When(
  new RegExp(`^I have navigated to the "([^"]+)" page by (${deviceList.join('|')})$`),
  (pageName: string, device: typeof deviceList[number]) => {});

When(
  `^I have navigated to the "([^"]+)" page by (${deviceList.join('|')})$`,
  (pageName: string, device: typeof deviceList[number]) => {});
```

**Comment by bm-stschneider** [comment]
I experience the same problem but without regex. sometimes the ui says can't find and with others from the same file it is found. But go to definition works for both.

**Comment by alexkrechik** [comment]
> **Describe the bug**
> The autocomplete does not recognize a step that uses the `new RegExp()` constructor instead of a regex literal
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> Please see the step definition and gherkin provided below.
> 
> **Expected behavior**
> The autocomplete should recognize steps that are defined with the RegExp constructor.
> 
> ![image](https://user-images.githubusercontent.com/18381801/62322313-670dc700-b46a-11e9-8ca8-88b74746b44e.png)
> 
> Literal regex are clear and concise, but lack any ability to re-use patterns that are shared by multiple steps.
> 
> **Screenshots**
> The step defined with the RegExp constructor is not recognized.
> ![image](https://user-images.githubusercontent.com/18381801/62321443-43e21800-b468-11e9-9ec0-ad7275045e55.png)
> 
> The step defined with a regex literal is recognized as expected.
> ![image](https://user-images.githubusercontent.com/18381801/62321516-755ae380-b468-11e9-8b23-f2dd6ce2cfeb.png)
> 
> **Cucumberautocomplete part of VSCode settings:**
> 
> ```
> {
>     "cucumberautocomplete.steps": ["./test/steps/**/*.steps.js"],
> }
> ```
> 
> **Step definition:**
> _test/steps/Given.steps.js_
> 
> ```js
> // Given(/^I have navigated to the "([^"]+)" page$/, pageName => {}); // Is recognized
> Given(new RegExp('^I have navigated to the "([^"]+)" page$'), pageName => {}); // Is not recognized 
> ```
> 
> **Gherkin step line**
> _test/features/example.feature_
> 
> ```
> Feature: Example
>     Scenario: Demonstrate the issue
>         Given I have navigated to the "Home" page
> ```
> 
> > Given I have navigated to the "Home" page

Hey! Sorry for the long response. If issue still valid for you - could you please try to use next option to fix this?
`    "cucumberautocomplete.gherkinDefinitionPart": "(RegExp)\\(",`

**Comment by alexkrechik** [comment]
> Also, it'd be great to be able to pass variables to the regular expressions!
> 
> ```
> // This is recognized
> When(
>   /^I have navigated to the "([^"]+)" page by (mobile|desktop)$/,
>   (pageName: string, device: string) => {});
> 
> // None of these are recognized
> const deviceList = ['mobile', 'desktop'] as const;
> When(
>   new RegExp(`^I have navigated to the "([^"]+)" page by (${deviceList.join('|')})$`),
>   (pageName: string, device: typeof deviceList[number]) => {});
> 
> When(
>   `^I have navigated to the "([^"]+)" page by (${deviceList.join('|')})$`,
>   (pageName: string, device: typeof deviceList[number]) => {});
> ```

Unfortunately, there is no ability to cover all the supported programming languages programmatic variables getting. As a workaround, "cucumberautocomplete.customParameters" option could be used like
```
"cucumberautocomplete.customParameters": [
        {
            "parameter":"${deviceList.join('|')})$",
            "value":"mobile|desktop"
        }
    ],
```

**Comment by alexkrechik** [comment]
> I experience the same problem but without regex. sometimes the ui says can't find and with others from the same file it is found. But go to definition works for both.

Could you please open the separate issue with examples, if this issue still valid for fou?

**Comment by alexkrechik** [comment]
Please reopen the issue if `"cucumberautocomplete.gherkinDefinitionPart": "(RegExp)\\(",` didn't help
