### ISSUE TITLE
Single quote usage for step params isn't recognised

### ISSUE THREAD

**Issue by Phonesis** [alexkrechik/VSCucumberAutoComplete#299]
It doesn't look like single quote usage is recognised when you add params to step definitions. For example, this is recognised:

    Then the "element" element is "displayed"

But this is not:

    Then the 'element' element is 'displayed'

For step definition:

```
Then('the {string} element is {string}', async () => {
    // code
  });
```

**Comment by Roaders** [comment]
yes, this is causing me issues as well. Upvote.

**Comment by DesHorsley** [comment]
The same issue is true for {word}

**Comment by kwakwaversal** [comment]
For reference, I've fixed this via `settings.json` by redefining `{string}` to my preferred single quote usage.

```javascript
{
  "cucumberautocomplete.customParameters": [
    {
    {
        "parameter": "{string}",
        "value": "'[^']+'"
    }
  ],
}
```

**Comment by adrian861** [comment]
Had the same problem after installing `eslint`.  Would be good to add this to extension support if common JS formatters are going the way of single quotes.

**Comment by dpresiana** [comment]
Workaround: If you want to support both single and double quotes you can redefine `{string}` like this
``` 
"cucumberautocomplete.customParameters": [
        {
            "parameter": "{string}",
            "value": "(?:'|\").*(?:'|\")" 
            
        }
]
```
