### ISSUE TITLE
Python - u prefix in string breaks Cucumber

### ISSUE THREAD

**Issue by PrzemekKrakow** [alexkrechik/VSCucumberAutoComplete#300]
**Describe the bug**
When I launching my old scenario, I cannot use them with Cucumber, because I have in my python steps after decorators (@given, @when, @then) string with u prefix.

**To Reproduce**
1. Open any file with steps.
2. Find any gherkin decorator, like: @given('the sun is shining')
3. Change them to: @given(u'the sun is shining')

**Expected behavior**
Cucumber should still recognize correct step for "Given the sun is shining" line in feature file. 
But I have message that cucumberautocomplete 'Was unable to find step for "Given the sun is shining".'

**Cucumberautocomplete part of VSCode settings:**
```
{
    "cucumberautocomplete.steps": [
        "project\\steps\\*.py"
    ],
    "cucumberautocomplete.syncfeatures": "project\\feature\\*feature",
    "cucumberautocomplete.strictGherkinCompletion": true
}
```

**Comment by alexkrechik** [comment]
Please try to use "cucumberautocomplete.customParameters" - looks like, that changing of `(u'` to `('` should help

**Comment by bv** [comment]
@alexkrechik, I have put these lines into settings.json:
```
    "cucumberautocomplete.customParameters": [
        {
            "parameter": "(u'",
            "value": "('"
        }
      ],
```
this configuration does help to navigate to step definition, but the `problems` are still reported:
```Was unable to find step for "Then step goes here" cucumberautocomplete```

**Comment by alexkrechik** [comment]
Closed due to this is proper behavior. If `cucumberautocomplete.strictGherkinCompletion` is true - `step goes here` should be used with `given` gherkin word only.
