### ISSUE TITLE
Special characters cause table layout to be skewed

### ISSUE THREAD

**Issue by vincentdebruijn** [alexkrechik/VSCucumberAutoComplete#301]
**Describe the bug**
When a table contains a special character, such as €, the automatic table layout doesn't align the columns.
On version 2.14.1

**To Reproduce**
Make a step with a table, such as:
| foo   | bar |
| € 20 |   | 

After saving it looks like the screenshot.

**Expected behavior**
I expect it to align the pipe characters.

**Screenshots**
![bug](https://user-images.githubusercontent.com/922611/67368802-3d9b9d80-f578-11e9-9587-717b1482d01f.png)

**Comment by alexkrechik** [comment]
Should be fixed in some previous PR
