### ISSUE TITLE
Support absolute path for cucumberautocomplete.steps ?

### ISSUE THREAD

**Issue by longk15t** [alexkrechik/VSCucumberAutoComplete#313]
Hi @alexkrechik 

I have a step definition directory which is outside of my main workspace directory and for some reason I can't include it to the project directory, should we support finding steps in these directories with absolute path ?

**Comment by alexkrechik** [comment]
As a solution, relative 'upper' path to this project could be used - ex. `"cucumberautocomplete.steps": ["steps/*.js", "../test.js"],` will look to the `test.js` in the parent of current project dir.

**Comment by lengors** [comment]
> As a solution, relative 'upper' path to this project could be used - ex. `"cucumberautocomplete.steps": ["steps/*.js", "../test.js"],` will look to the `test.js` in the parent of current project dir.

Sorry for reopening this, but is there a plan to add support for absolute paths?

The solution provided does partially work, but it's quite cumbersome if we have multiple projects on multiple different subfolders.
