### ISSUE TITLE
Having trouble getting autocomplete to work for C# specflow

### ISSUE THREAD

**Issue by fallXone** [alexkrechik/VSCucumberAutoComplete#315]
Hello, I'm having issues getting this extension to work. Specifically, the autocomplete portion.

All of our steps are named *Steps.cs
All feature files are .feature

I have the settings configured like so

```
"cucumberautocomplete.steps": [
        "**/*Steps.cs"
	],
	"cucumberautocomplete.syncfeatures": "**/*.feature",
        "cucumberautocomplete.strictGherkinCompletion": true
```

and I've set up a workspace containing the folder with our specflow steps. The "Gherkin step autocomplete" extension works for me, but this extension does not. I would prefer to just use this extension. Thanks!

**Comment by VJose6** [comment]
What was the resolution?
