### ISSUE TITLE
autoformat with unicode characters (table section)

### ISSUE THREAD

**Issue by bbarkenovdocdocru** [alexkrechik/VSCucumberAutoComplete#328]
Running autoformat for table does not correctly for non-ascii:

http://joxi.net/xAeygYyCRx060A

**Comment by alexkrechik** [comment]
This error happens due to the different width of the different symbols. We have tried to fix this by some other PR, but, looks like, this should be reviewed.

**Comment by tungtrinh** [comment]
> This error happens due to the different width of the different symbols. We have tried to fix this by some other PR, but, looks like, this should be reviewed.

this one https://github.com/alexkrechik/VSCucumberAutoComplete/pull/278

**Comment by ledenis** [comment]
I think we take inspiration from prettier for calculating width of characters: 
https://github.com/prettier/prettier/blob/464883602c33959fb08b73180b3edb052970e548/src/common/util.js#L543

**Comment by ledenis** [comment]
HI @alexkrechik, could you merge this https://github.com/alexkrechik/VSCucumberAutoComplete/pull/341 ?

This bug is irritating since it happens with currency symbols €, $, etc... and we use them a lot in tables in our tests...

**Comment by bursauxa** [comment]
Same as @ledenis currency symbols are standard width, but will be ignored, which is annoying because they are quite common.

(note that he mentioned `$` which does work because it's actually ASCII, but for sure € does not, and it's not the most exotic of currencies)

**Comment by alexkrechik** [comment]
Sorry for the long response. I'm planning to merge this and all the other ready PR's this week.

**Comment by ledenis** [comment]
Now that it is merged, would it be possible to publish a release with this fix soon?

**Comment by alexkrechik** [comment]
Yeah, will publish after fix the issue with prepublish script.
