### ISSUE TITLE
Can't set another language but English in Features

### ISSUE THREAD

**Issue by analiviaalmeida** [alexkrechik/VSCucumberAutoComplete#331]
**Describe the bug**
Hey,
I am new in Gherkin and I am trying to write features in my native Language (Portuguese), but I am not getting the higlights and autcomplete when I type the snippets in Portuguese. 

I've been using the command "# language: pt" at the first line of my .feature files, but it's not working as I expected. I've been wondering if this command is supported by the extension.

Am I missing something here? Apparently, installing the extension and putting that command at the first line should be enough.

English:
![image](https://user-images.githubusercontent.com/47273027/79383137-11ffdb80-7f3b-11ea-999b-6f304138ec4e.png)

Portuguese:
![image](https://user-images.githubusercontent.com/47273027/79383214-31970400-7f3b-11ea-9882-a5392fb6a6f1.png)

**Comment by alexkrechik** [comment]
Hey! All the words for all the languages should be present in extension. Otherwise, they should be added manually. You could create PR for this or list all the required words here, so I would add them.

**Comment by alexkrechik** [comment]
Please, reopen this issue with examples of words with no highlight if the issue still valid for you. Thank you.

**Comment by barraponto** [comment]
Still doesn't work for me. I see it has support for other languages, but I can't figure out how to enable it.

**Comment by okrechyk-gb** [comment]
It should be enabled by default.

**Comment by alexkrechik** [comment]
Should be enabled by default.
