### ISSUE TITLE
Unable to sync Feature file with Step definitions in my project. Everything looks fine, yet it's unsuccesful.

### ISSUE THREAD

**Issue by spjagadeesh** [alexkrechik/VSCucumberAutoComplete#332]

**Comment by inampude** [comment]
I'm too facing the same issue, though I applied these steps on both settings.json files.

**Comment by spjagadeesh** [comment]
> I'm too facing the same issue, though I applied these steps on both settings.json files.

Hope and Believe someone from the team, might help us, if something wrong what we have configured in our project or the path we provided in the settings.json. Lets wait for them. Meanwhile if you're able to find the solution, please drop a note here or to spjworld@gmail.com. I'd be glad to see the solutions..!! Thanks in advance.

**Comment by alexkrechik** [comment]
Could you please provide step definition example? I'll try to reproduce it.

**Comment by spjagadeesh** [comment]
> Could you please provide step definition example? I'll try to reproduce it.

@alexkrechik Mine is a intranet application, so I'm afraid you won't be able to run at your Local desktop. I'm sure the extension will work for you, because I believe there is some workspace issue which is causing this issue to occur in settings.json file.
**Settings.json file path** : C:\Users\Z029480\AppData\Roaming\Code\User\settings.json
Is it the same for you too?

**My project structure:**
-PROJECT NAME
  -featureFiles
    -features1.feature
    -features1.feature
  -stepDefinitions
    -stepDefintions_1.ts
    -stepDefintions_2.ts
    -stepDefintions_3.ts
  -pageObjects
  -logs
  -configFiles
  -commonUtlities
  -node_modules
  -reports
  -package.json
  -ts-config.json

**Settings.json file:**
{
    "cucumberautocomplete.steps": ["stepDefinitions/*.ts"],
    "cucumberautocomplete.syncfeatures": "featureFiles/*feature",
    "cucumberautocomplete.strictGherkinCompletion": true,
    "cucumberautocomplete.strictGherkinValidation": true,
    "cucumberautocomplete.smartSnippets": true,
    "cucumberautocomplete.stepsInvariants": true,
    "workbench.iconTheme": "vscode-icons",
    "files.autoSave": "afterDelay"
}

**Feature File:**
Feature: 1446_UC_DeleteIconValidation

Scenario: TC01_Validate whether user is able to delete an Excel file using Delete icon and upload another file when Use case is in Specify status
        Given User navigates to Use case dashboard page
        When User opens the newly created Use case

**StepDefinitions Sample:**
import { Given, When, Then } from 'cucumber';
import { browser, element, by } from 'protractor';
import { HeaderTab } from '../pageObjects/HeaderTab';
import { UC_CreationPage } from '../pageObjects/UC_CreationPage';
import { UC_DashboardPage } from '../pageObjects/UC_DashboardPage';
import { UC_DetailsPage } from '../pageObjects/UC_DetailsPage';
import { CommonMethods } from "../commonUtlities/CommonMethods";
import { LOGTYPE } from "../Constants/enums";

let uc_CreationPage = new UC_CreationPage();
let uc_DashboardPage = new UC_DashboardPage();
let uc_DetailsPage = new UC_DetailsPage();
let headerTab = new HeaderTab();
let cmm = new CommonMethods();

Given('User navigates to Use case dashboard page', async () => {
  await cmm.clickElement(await headerTab.usecasesTab)
  await cmm.udpateLog(LOGTYPE.INFO, "Clicked on Use case tab")
  await cmm.assertElementEqualString(await uc_DashboardPage.pageName, "Use cases")
  await browser.sleep(2000)
});
When('User opens the newly created Use case', async () => {
  await cmm.sendKeysToElement(await uc_DashboardPage.searchTextBox, await cmm.readProjectPropJSON("UsecaseName"))
  await cmm.udpateLog(LOGTYPE.INFO, "Entered the Search keyword : " + await cmm.readProjectPropJSON("UsecaseName"))
  await browser.sleep(3000)
  await cmm.clickElement(await uc_DashboardPage.getUseCaseUsingName(await cmm.readProjectPropJSON("UsecaseName")))
  await cmm.udpateLog(LOGTYPE.INFO, "Clicked on Use case with name : " + await cmm.readProjectPropJSON("UsecaseName"))
  await cmm.waitForVisibilityOfElement(uc_DetailsPage.useCaseName)
  await cmm.assertElementEqualString(await uc_DetailsPage.useCaseName, await cmm.readProjectPropJSON("UsecaseName"), "Opened Use case successfully")
});

**Comment by spjagadeesh** [comment]
@alexkrechik  Any updates? Waiting to see a solution.

**Comment by MargareteGretlM** [comment]
I am having the same issue as does my colleagues.

**Comment by Eduardo-Carneiro-CM** [comment]
Anyone found a solution yet?

**Comment by nair-sumesh** [comment]
Can you try removing all config settings. and then start adding one by one.
(will have to manually restart VSC after each change and wait for the extensions to load.)

My settings.json currently only has 
**cucumberautocomplete.steps** and 
    **cucumberautocomplete.syncfeatures**

**Comment by Eduardo-Carneiro-CM** [comment]
Only with that 2 I still have problems

**Comment by Eduardo-Carneiro-CM** [comment]
No in order to try this I'm only using one specific file

**Comment by Eduardo-Carneiro-CM** [comment]
```javascript
{
    "cucumberautocomplete.steps": [
        "../cypress/integration/common/*.js",
    ],
    "cucumberautocomplete.syncfeatures": "../cypress/integration/Features/*.feature",
}
```

**Comment by nair-sumesh** [comment]
hmmm, sorry for the confusion, mine is a Java project. JS should also work , however @alexkrechik  will be the best person to guide you.

**Comment by Eduardo-Carneiro-CM** [comment]
No problem still thank you for the help

**Comment by Akuukis** [comment]
I got a similar problem with workspaces, and it helped to add a `../` at the start of path, because for some reason in my setup it looked for files **relative to** workspace settings file.

**Comment by igorrmotta** [comment]
The workaround above solves my problem!!

**Comment by jameshughes7** [comment]
I'm having the same problem as above. Unable to step into steps file from feature file. Without the ability to navigate to the step, it just takes so much more time.

**This is my folder structure:**
![image](https://user-images.githubusercontent.com/30200120/94208865-c1fe4b00-fec2-11ea-9ebd-ead0a61315e2.png)

**package.json**
```
"dependencies": {
    "cypress": "^5.1.0",
    "cypress-cucumber-preprocessor": "^2.5.5",
    "prettier": "^2.1.1"
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "stepDefinitions": "cypress/integration"
  }
```

**plugins/index.js **
```
const cucumber = require('cypress-cucumber-preprocessor').default;

module.exports = (on, config) => {
  on('file:preprocessor', cucumber());
}
```

**.vscode/settings.json**
```
{
    "cucumberautocomplete.steps": [
        "cypress/integration/**/*.js",
        "cypress/integration/common/*.js",
    ],
    "cucumberautocomplete.syncfeatures": "cypress/integration/*.feature",
    "cucumberautocomplete.strictGherkinCompletion": true
}
```

Any help would be greatly appreciated. Thanks
