### ISSUE TITLE
In steps files autocomplete / jump to step definition does not working

### ISSUE THREAD

**Issue by y4rk4s** [alexkrechik/VSCucumberAutoComplete#334]
**Describe the bug**
Ctrl+Click , F12 does not find definition in steps files

**To Reproduce**
Example code:
Feature file, create following:
`And Something`
Press F12 on Something
Will jump on the related step file:
```
@step('Something')
_def step_impl( c ):_
```
Press F12 on @step

**Expected behavior**
Jump to definition in feature file

**Actual behavior**
'No definition found' message is appears, also in Step file auto-complete does not working

**Cucumberautocomplete part of VSCode settings:**
```
   "cucumberautocomplete.syncfeatures": "ABC/EFG/something/*feature",
    "gherkin-autocomplete.featuresPath": "ABC/EFG/something",
    "editor.quickSuggestions": true,

    "python.autoComplete.extraPaths": ["system" ],
    "cucumberautocomplete.steps": [
        "ABC/EFG/something/*.py",
 
        ],

     "cucumberautocomplete.strictGherkinValidation" :true,	
    "cucumberautocomplete.strictGherkinCompletion": true,
    "cucumberautocomplete.onTypeFormat": true,

```

**Comment by alexkrechik** [comment]
Unfortunately, this extension could control only `.feature` files and `.gherkin` files.
