### ISSUE TITLE
Feature steps with Integers are not identified by the extension

### ISSUE THREAD

**Issue by nair-sumesh** [alexkrechik/VSCucumberAutoComplete#335]
##### Feature File
underlined in red
- Then Table row 1 has 0 user shares

##### Step File
- @Then("^Table row 1 has (\\d+) user shares$")

**Comment by alexkrechik** [comment]
Are these steps properly identified by the cucumber itself?

**Comment by nair-sumesh** [comment]
Yes. The cucumber framework works perfectly. 
Btw I found a workaround. By replacing (\+d) with  ([0-9]+) .
I believe this  extension’s parser does recognize the wildcard \d.

This workaround is not a best solution as this change would have to be implemented for all exiting steps (including from other authors). Which I don’t prefer.

I would appreciate if this issue could be fixed.
Thanks for your support.

**Comment by alexkrechik** [comment]
Strange, but this looks good for me.
<img width="534" alt="Screen Shot 2020-07-04 at 7 55 07 PM" src="https://user-images.githubusercontent.com/5772406/86517279-62971e80-be30-11ea-96f6-570c22f32c2b.png">
<img width="489" alt="Screen Shot 2020-07-04 at 7 55 32 PM" src="https://user-images.githubusercontent.com/5772406/86517281-64f97880-be30-11ea-85c4-36be9ee65fbc.png">
