### ISSUE TITLE
Feature request: Support "relative to following line" in formatConfOverride

### ISSUE THREAD

**Issue by martling** [alexkrechik/VSCucumberAutoComplete#343]
I try to follow the Cucumber (1) or SpecFlow (2) reference on how to indent tags and comments. But when I use CucumberAutoComplete's auto format it breaks my intended indentation.

I would like a tag/comment to have the same indentation as the following element (e.g. Feature or Scenario). formatConvOverrides does not allow the user to indent a keyword in relation to the following line but only to the previous line.

e.g.
"cucumberautocomplete.formatConfOverride": {
        "@": "relative"
}

You provide an very nice tool for writing Gherkin in VSC and it would be great if you could extend it in this regard.

(1) :https://cucumber.io/docs/cucumber/api/#tags
(2): https://docs.specflow.org/projects/specflow/en/latest/Gherkin/Gherkin-Reference.html

**Comment by alexkrechik** [comment]
Looks like, that 'relativeNext' option is required or something like this.

**Comment by alexkrechik** [comment]
Should be fixed after 2.16.0 release using 'relativeUp' option when required.

**Comment by alexkrechik** [comment]
Same problem with https://github.com/alexkrechik/VSCucumberAutoComplete/issues/378

**Comment by alexkrechik** [comment]
This issue is to be fixed or implemented in the 3.0.0 version of the extension. If this issue is unresolved or there are additional notes, please create a new ticket with the necessary details.
