### ISSUE TITLE
[bug] Step detection doesn't match lines containing parenthesis or colon characters

### ISSUE THREAD

**Issue by karlfus** [alexkrechik/VSCucumberAutoComplete#349]
Could be related to https://github.com/alexkrechik/VSCucumberAutoComplete/issues/166

If a line contains parenthesis or colon characters, the steps are not found.

In the images below, the steps with matching names exist, but they are flagged as "unable to find step":

![image](https://user-images.githubusercontent.com/2079676/90245036-cb0eed80-de29-11ea-9f15-d391b6d43f07.png)

![image](https://user-images.githubusercontent.com/2079676/90245052-d530ec00-de29-11ea-929e-0fc7bf674a5e.png)

**Comment by alexkrechik** [comment]
Could you please provide step definitions for these steps?

**Comment by pfoucray** [comment]
Hi !
I have similar issues but with  the scenario outline and its step followed by an example.
We went for the #fr version of cucumber .feature files.
see screenshot.
Is there something I'm missing ?

![image](https://user-images.githubusercontent.com/16115517/108082386-533cac80-7072-11eb-99b1-11ab93f31a6e.png)
![image](https://user-images.githubusercontent.com/16115517/108082456-68b1d680-7072-11eb-9fa5-96e15dd0ed74.png)

**Comment by alexkrechik** [comment]
Should be fixed now.
