### ISSUE TITLE
support steps defined with strings instead of regexes

### ISSUE THREAD

**Issue by capaj** [alexkrechik/VSCucumberAutoComplete#35]
steps which are defined with strings are not autocompleted

**Comment by alexkrechik** [comment]
Looks like new format should be supported without any code changes. Do you have any unsupported cases examples ?

**Comment by capaj** [comment]
@alexkrechik will post a sample

**Comment by capaj** [comment]
@alexkrechik I've just made the simplest possible [cucumber-js sample](https://github.com/capaj/cucumber-js-sample) and there I get the squiggly lines: 

![Imgur](http://i.imgur.com/b5Xw9Ln.png)

And no autocomplete:

![Imgur](http://i.imgur.com/zwqd2Kf.png)

**Comment by alexkrechik** [comment]
Looks like, steps definitions first argument should be regexp's (https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#200-rc4-2016-12-19):
defineSupportCode(function({Given, setWorldConstructor}) {
  Given(**/^a step$/**, function() {});
  setWorldConstructor(CustomWorld);
});

But, in your app, step definitions first argument type is string:
  Given(**'I am on the Cucumber.js GitHub repository'**, function () {
    return this.driver.get('https://github.com/cucumber/cucumber-js/tree/master')
  })

Are you sure, that they are valid?

**Comment by capaj** [comment]
@alexkrechik of course they are. you can try it out by installing deps and running `./node_modules/.bin/cucumber-js`

The sample is taken from the official documentation here: https://github.com/cucumber/cucumber-js/blob/master/docs/nodejs_example.md

**Comment by capaj** [comment]
@alexkrechik so I tried with regexes and you were right-those work just fine. Thanks for your response. I will rename this bug then.

**Comment by alexkrechik** [comment]
Will be fixed with https://github.com/alexkrechik/VSCucumberAutoComplete/issues/39 in the nearest release.

**Comment by alexkrechik** [comment]
Should be fixed in 2.1.0 version of plugin
