### ISSUE TITLE
Does this extension work with VS Code Version 1.48?

### ISSUE THREAD

**Issue by ChapelTandel** [alexkrechik/VSCucumberAutoComplete#351]
Go to Step Definition isn't working for me.

I am seeing the yellow swirly line under the gherkin text.

I am using the latest VSCode Version 1.48.2.

Did anyone get it working with this version of VSCode?

I am using Cucumber with JS.

**Comment by alexkrechik** [comment]
The extension should work with any version of VSCode. If there are errors like 'Was unable to find definition for the line', please ensure that extension settings are correct. You could update the ticket with step definition example and extension setting for this problem debugging.

**Comment by ChapelTandel** [comment]
Hi Alex,

Thanks for the quick response. 

Please find the sted def and settings below:


**Step definition:**

import {Given, When, Then} from 'cucumber'
import appFormPage from '../pageobjects/AppFormPage'

Given(/^I am on appForm page$/, ()=>{
    appFormPage.Open();
})

When(/^I apply for an account$/, ()=>{
    appFormPage.Populate();
})

Then(/^I see thank you page$/, ()=>{
    console.log('World')
})


**Settings.json**

{
    "window.zoomLevel": 2,
    "workbench.iconTheme": "vscode-icons",
    "vsicons.dontShowNewVersionMessage": true,
    
    "cucumberautocomplete.steps": [
        "features/step-definitions/*.js"
    ],
    "cucumberautocomplete.strictGherkinCompletion": true,
    "cucumberautocomplete.syncfeatures": "features/*.feature",
    "cucumberautocomplete.onTypeFormat": true,
    "cucumberautocomplete.stepsInvariants": true,
    "cucumberautocomplete.strictGherkinValidation": true,
    "cucumberautocomplete.customParameters": [
    
    ]

}


The tests are running fine, so the features are connected to the steps correctly. 

![2020-09-10_20-16-20](https://user-images.githubusercontent.com/5759239/92790370-a31c9680-f3a3-11ea-8b1d-91be13095cdb.jpg)

![2020-09-10_20-15-37](https://user-images.githubusercontent.com/5759239/92790393-a748b400-f3a3-11ea-95f9-95cf26963c05.jpg)

**Comment by ChapelTandel** [comment]
@alexkrechik any update on this?

**Comment by ChapelTandel** [comment]
@alexkrechik could you please look into this!

**Comment by alexkrechik** [comment]
Please provide step definitions for the steps from screen (ex. 'I am on the login page). Was id declared via 'Given' word?

**Comment by alexkrechik** [comment]
Possible reasons for your problem are:
1. Different declaration and feature gherkin words (Please provide step definitions for the steps from the screen (ex. 'I am on the login page). Was id declared via 'Given' word?)
2. Wrong path to the steps in settings (do you see any warnings there?).

**Comment by ChapelTandel** [comment]
It's all working fine now, and I haven't changed anything. 

I remember updating my Windows OS.

**Comment by ChapelTandel** [comment]
Happy to close this issue.
