### ISSUE TITLE
Peek Definition: Unable to find step for "When receive the response code 202"

### ISSUE THREAD

**Issue by liangzhu2000** [alexkrechik/VSCucumberAutoComplete#352]
I have the following step definition:
```
@When("^receive the response code (\\d+)$")
public void getResponse(int responseCode) {
         ...
	}
```

Configured the setting as following:
```
"cucumberautocomplete.customParameters": [
        {
            "parameter":"(\\d+)",
            "value":"d+"
        }
    ],
```

The definition peeking does not work. Is this due to my wrong configuration? Or the custom parameter feature does not support data types other than string?

**Comment by alexkrechik** [comment]
Were all the other steps properly found? Custom parameter feature should work anyway, the only potential problem I see here - number of backslashes.

**Comment by liangzhu2000** [comment]
Hi @alexkrechik ,

Please check Case 1 and Case 2 in **.feature** and **.java** sections. All instances like case 1 can be found. None of case 2 can be found.

My `settings.json` for Cucumber Auto Complete settings is shown as follows:

    "cucumberautocomplete.customParameters": [
        
        { "parameter":"(\\d+)", "value":"d+" },
        { "parameter":"\"([^\"]*)\"", "value":".*" },
    ]
The 2nd parameter works, but not the first one that is mapped to an integer. Any idea how I can configure the parameter?
### .feature
_Case 1_:
        When specify the image tag "0.1.1"
_Case 2_:
        When query service by name, get response 200
### .java
_Case 1_:
         @When("^specify the image tag \"([^\"]*)\"$")
         public void specifyServiceName(String tag) {
_Case 2_:
	@When("^query service by name, get response (\\d+)$")
	 public void queryServiceByNameGetResponse(int responseCode) {
