### ISSUE TITLE
Click through to the definition does not work for newer Gerkin syntax {string}

### ISSUE THREAD

**Issue by jb** [alexkrechik/VSCucumberAutoComplete#355]
**Describe the bug**
Click through to the definition does not work for newer Gerkin syntax {string}

**To Reproduce**
1. have a step definition 
`Then('the custom segment {string} is available') do |expected_segment|
  expect(@actual_segment).to include expected_segment
end
`
2. create a step in a feature file
` Then the custom segment 'Custom segment' is available`
3. try to click through
4. See error `Was unable to find step for "And the standard segment 'Food and Beverage > Casual Dining > Asian(NinthDecimal)' is available"cucumberautocomplete`

**Expected behavior**
You are able to click to the step definitions

This works if I change the step def to 
`/^the custom segment (.*) is available$/`
however I would like to use the new cucumber way

**Cucumberautocomplete part of VSCode settings:**
```
    "cucumberautocomplete.onTypeFormat": true,
    "cucumberautocomplete.smartSnippets": true,
    "cucumberautocomplete.stepsInvariants": true,
    "cucumberautocomplete.steps": [
        "features/step_definitions/*.rb",
    ],
    "cucumberautocomplete.syncfeatures": "features/*feature"
```

**Comment by alexkrechik** [comment]
Actually, `{string}` is changing by `"[^"]+"`.

**Comment by jb** [comment]
Is there something I need to change in my config for autocomplete to match to {string}?

**Comment by alexkrechik** [comment]
I'll fix this in the future, but as  temporary fix you could try `"cucumberautocomplete.customParameters"` option to change `{string}` with `'[^']+'`

**Comment by jb** [comment]
The following worked thanks!
`    "cucumberautocomplete.customParameters": [

        {
            "parameter": "{string}",
            "value": "'[^']+'"
        }
    ],`
