### ISSUE TITLE
List Format?

### ISSUE THREAD

**Issue by comerc** [alexkrechik/VSCucumberAutoComplete#359]
expectation:

![Снимок экрана от 2020-11-04 06-49-01](https://user-images.githubusercontent.com/1025241/98067121-e823ed00-1e69-11eb-9c8e-9c4e5437553e.png)

reality:

![Снимок экрана от 2020-11-04 06-49-46](https://user-images.githubusercontent.com/1025241/98067154-fa059000-1e69-11eb-83b6-5eccc0418312.png)

please help me :)

**Comment by comerc** [comment]
only with `#language: ru`

**Comment by alexkrechik** [comment]
Let's see if it would be fixed in 1.15.1. I will do some formatting fixes there.

**Comment by alexkrechik** [comment]
This issue is to be fixed or implemented in the 3.0.0 version of the extension. If this issue is unresolved or there are additional notes, please create a new ticket with the necessary details.
