### ISSUE TITLE
Feature Request: Outline View

### ISSUE THREAD

**Issue by p2635** [alexkrechik/VSCucumberAutoComplete#362]
It would be a good if an outline view of a given feature could be shown here. This will be be easier to move between scenarios for navigation.

![image](https://user-images.githubusercontent.com/4522927/98667538-6e4aa280-2346-11eb-8f5d-eff677942a52.png)

It would look something like this:
Feature: First line of the feature
Rule: Rule 1
   Example: Example 1
Scenario: Bob 1
Scenario: Bob 2
Scenario: Bob 3
Scenario: Bob 4

**Comment by Jargonius** [comment]
This is very much needed.
