### ISSUE TITLE
Duplicated declarations

### ISSUE THREAD

**Issue by kmisiag** [alexkrechik/VSCucumberAutoComplete#371]
Hi, 
I declared following steps: 

this.When(/^I wait for success screen dismissed$/, function (next) {
    next;
});

this.And(/^I wait for success screen dismissed$/, function (next) {
    next;
});

this.Then(/^I wait for success screen dismissed$/, function (next) {
    next;
});

But autocompletion and validation works only for one of them.

**Comment by alexkrechik** [comment]
Validation will work separately in case of "strict gherkin validation" option usage. But, anyway, this is a good point - to try to get proper gherkin word in the code if gherkin strict mode enabled.

**Comment by kmisiag** [comment]
Ok, but I don't understand why it seems like other two steps are overwritten by the first one with strict mode enabled and autocompletion and validation doesn't works for them

**Comment by alexkrechik** [comment]
Because many (or most) cucumber framework see no difference between `this.When` and `this.And`and definitions and will take the first found.
