### ISSUE TITLE
How to declare steps for other programming languages?

### ISSUE THREAD

**Issue by JornWildt** [alexkrechik/VSCucumberAutoComplete#416]
We are using C# (Xunit.Gherkin.Quick) for implementing Gherkin steps. How can we tell VSCucumberAutoComplete to recognize the C# implementation of these steps and add autocompletion for them?

I do not expect VSCucumberAutoComplete to be able to parse C# code (but perhaps it does?), but I would like to know if we can export the step patterns to a separate file that VSCucumberAutoComplete can then read?

The most obvious implementation would be to auto-transform the C# attributes using in Xunit.Gherkin.Quick to JavaScript and then let VSCucumberAutoComplete interpret that ... but is there a better way?

**Comment by okrechyk-gb** [comment]
The Gherkin format is the same for any programming language.
Steps definition not the same, but way extension getting them allow to get steps from the most programming languages like:
```
@When('I do something')
when(/I do something/)
```
So, may be, extension will work properly with `C#`. Otherwise, there are some options that could help to correct steps definition format.

**Comment by alexkrechik** [comment]
The Gherkin format is the same for any programming language.
Steps definition not the same, but way extension getting them to allow to get steps from the most programming languages like:
```
@When('I do something')
when(/I do something/)
```
So, maybe, the extension will work properly with C#. Otherwise, there are some options that could help to correct the steps definition format.

**Comment by JornWildt** [comment]
Xunit.Gherkin.Quick uses `@When('I do something')` like below, so, in theory, it might work out of the box?

    [When(@"I execute task (\w+)")]
    public void ExecuteTask(string taskKey)
    {
      ....
    }

I wasn't able to figure out how to point VSCucumberAutoComplete  to the C# files, but I'll give it a try more. Thanks.

Next question is of course if VSCucumberAutoComplete can use reflection in .NET to inspect the proper attributes in the compiled DLL's ... I gues not :-)

**Comment by alexkrechik** [comment]
Maybe everything will not work by default due to the '@' symbol.You could try something like:
```
"cucumberautocomplete.customParameters": [
        {
            "parameter":"(@",
            "value":"("
        },
    ],
```

Regarding reflection in .NET - not sure, but looks like that it will not work.

**Comment by JornWildt** [comment]
Thanks for your input. It works fairly well - there are some issues with regex interpretation, but most of these can be overcome by using cucumber expressions instead.

Speaking of those expressions - in `steps.handler.ts` you transform `{float}`, `{int}`, `{string}`, `{stringInDoubleQuotes}` and `{}` - but `stringInDoubleQuotes` is not part of the standard (see https://github.com/cucumber/cucumber-expressions#readme) - and you are missing `{word}`. Have I missed something or should they be included?

**Comment by alexkrechik** [comment]
looks like that `{stringInDoubleQuotes}` was added by special request. Regarding `{word}` - looks like, that it should be added, it wasn't in standard when I worked on this part.

**Comment by JornWildt** [comment]
Okay. Lets close this issue then - I'll added a request for `{word}´. See https://github.com/alexkrechik/VSCucumberAutoComplete/issues/417. Thanks.
