### ISSUE TITLE
Add support for cucumber expression {word}

### ISSUE THREAD

**Issue by JornWildt** [alexkrechik/VSCucumberAutoComplete#417]
Please add support for {word} as a cucumber expression (see https://github.com/cucumber/cucumber-expressions#readme).

**Comment by olenitsj** [comment]
Please with this issue look also at:

`step = step.replace(/{string}/g, '"[^"]+"'); ` in steps.handler.ts 

As the cucumber expression specification states: 
`
Matches single-quoted or double-quoted strings, for example "banana split" or 'banana split' (but not banana split). Only the text between the quotes will be extracted. The quotes themselves are discarded. Empty pairs of quotes are valid and will be matched and passed to step code as empty strings.`


Currently {string} cucumber expression does not work for:
1. `""` it should match an empty string. 
2. `''` it should match an empty string. 
3. 'Some Text! 123.' it should match `Some Text! 123.`

**Comment by olenitsj** [comment]
@JornWildt 

I have added the {word} expression in https://github.com/alexkrechik/VSCucumberAutoComplete/pull/418
If @alexkrechik will have some time he could merge my pr and package it with the next release.
