### ISSUE TITLE
Please add  VSCucumberAutoComplete to Open VSX registry

### ISSUE THREAD

**Issue by BrianGilbert** [alexkrechik/VSCucumberAutoComplete#422]
**Describe the bug**
We use gitpod which gives you vscode ion the cloud, it is connected to Open VSX registry meaning that it's not currently possible to install this addon. https://www.gitpod.io/docs/vscode-extensions/

Can you please add it to the Open VSX Registry?
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by alexkrechik** [comment]
https://open-vsx.org/extension/alexkrechik/cucumberautocomplete
