### ISSUE TITLE
Warning in "And" clauses

### ISSUE THREAD

**Issue by carri747** [alexkrechik/VSCucumberAutoComplete#435]
**Describe the bug**
I've a lot of warning in feature files in "And" clauses. The thing is that VS find the step but the warning is ugly

**To Reproduce**
1. Define a step in with "Given" condition
2. Reuse this step in a "When" or "Then" condition

**Expected behavior**
If the step is there defined as "Given", "When" or "Then" make not sense that the "And" show a warning

**Screenshots**
![image](https://user-images.githubusercontent.com/22347831/164439882-32cfad11-7569-4c78-8294-dad8d6b23656.png)

**Cucumberautocomplete part of VSCode settings:**
```
{
    "cucumberautocomplete.steps": ["src/stepDefinitions/**/*.ts"],
    "cucumberautocomplete.syncfeatures": "src/features/**/*.feature",
    "cucumberautocomplete.strictGherkinCompletion": true,
    "cucumberautocomplete.strictGherkinValidation": true,
    "cucumberautocomplete.smartSnippets": true,
    "cucumberautocomplete.stepsInvariants": true,
    "cucumberautocomplete.customParameters": [
        {
            "parameter":"{ab}",
            "value":"(a|b)"            
        }
    ],
    "cucumberautocomplete.pages": {
        "common": "src/pageObject/commonPageObject.ts"
    },
    "cucumberautocomplete.skipDocStringsFormat": true,
    "cucumberautocomplete.formatConfOverride": {
        "And": 3,
        "But": "relative"
    },
    "cucumberautocomplete.onTypeFormat": true,
    "editor.quickSuggestions": {
        "comments": false,
        "strings": true,
        "other": true
    },
    "cucumberautocomplete.gherkinDefinitionPart": "(Given|When|Then|defineStep)\\(",

    "prettier.trailingComma": "none",
    
}

```
VS version: 1.66.2
Cucumber plugin: 2.15.2

**Comment by youssef-t** [comment]
If you want to reuse steps with other keywords, the configuration file must have these two parameters set to false as following:
```
"cucumberautocomplete.strictGherkinCompletion": false,  
"cucumberautocomplete.strictGherkinValidation":  false,
```

Reference: [https://github.com/alexkrechik/VSCucumberAutoComplete#all-the-settings-description](https://github.com/alexkrechik/VSCucumberAutoComplete#all-the-settings-description)

**Comment by carri747** [comment]
Thanks a lot, it's working
