### ISSUE TITLE
Step definition with triple quotes in scala does not work

### ISSUE THREAD

**Issue by hoangong** [alexkrechik/VSCucumberAutoComplete#441]
**Describe the bug**
Scala """ quotes is not detected correctly.

**To Reproduce**
1. create a step in scala
```
class MySteps extends ScalaDsl with EN {

  Given("""my step""") { () =>
  }

}
```
2. Feature file does not detect "my step"
```
Given my step
```
5. However, if I change step definition to `Given("my step")` it works fine

**Expected behavior**
Work with scala triple quotes

**Screenshots**
![Screenshot 2022-06-25 at 15 15 56](https://user-images.githubusercontent.com/5703525/175777465-1c2b1131-00f0-42d8-a713-7f5ead747d6f.png)

**Cucumberautocomplete part of VSCode settings:**
```
  "cucumberautocomplete.steps": [
      "**/test/**/*.scala"
  ]
```

**Comment by alexkrechik** [comment]
`"cucumberautocomplete.stepRegExSymbol": "'''"` option would help you

**Comment by hoangong** [comment]
I added `"cucumberautocomplete.stepRegExSymbol": "\"\"\""` it helps. thank you
