### ISSUE TITLE
Syntax highlighting doesn't work in Themes other than vscode

### ISSUE THREAD

**Issue by puranjayjain** [alexkrechik/VSCucumberAutoComplete#446]
**Describe the bug**
Syntax highlighting doesn't work for third party color themes in vscode

**To Reproduce**
Select any other theme apart from the inbuilt vscode themes and syntax highlighting doesn't work.

**Expected behavior**
It should work.

**Screenshots**
<img width="1065" alt="Screenshot 2022-07-20 at 2 58 31 PM" src="https://user-images.githubusercontent.com/5458094/179948495-bc66fdfe-8702-47dc-84d9-7ab64d4f047b.png">

**Comment by alexkrechik** [comment]
Looks like that you was used the theme without some colorus support. I've tried all the defaults themes - looks ok for them:
<img width="457" alt="Screenshot 2022-07-28 at 10 02 42" src="https://user-images.githubusercontent.com/5772406/181442197-cb6feeae-bf6a-4f81-b887-514a10c76ee6.png">
<img width="311" alt="Screenshot 2022-07-28 at 10 02 31" src="https://user-images.githubusercontent.com/5772406/181442201-1c7b6707-82dc-45a6-b99d-3b61d7a1947f.png">
<img width="304" alt="Screenshot 2022-07-28 at 10 02 19" src="https://user-images.githubusercontent.com/5772406/181442204-ba0c7cb7-986d-4bc0-86a3-52184d309704.png">
<img width="463" alt="Screenshot 2022-07-28 at 10 02 06" src="https://user-images.githubusercontent.com/5772406/181442207-a487c0f5-d42c-4f9f-b436-45240a825b62.png">

**Comment by alexkrechik** [comment]
All the `Given`, `When` and `Then` are defined as `captures`. If color scheme support these types of entities - they would be highlighted. If not - then their colour would be the same with default text.

**Comment by puranjayjain** [comment]
Seems to me that the color theme above is outdated and needs an upgrade to fix it. @alexkrechik thanks for your reply.
