### ISSUE TITLE
Extension not updating on VSCode

### ISSUE THREAD

**Issue by JCTD** [alexkrechik/VSCucumberAutoComplete#449]
Hi, it doesn't appear that your merges are being updated on VSCode?
<img width="899" alt="Screen Shot 2022-08-01 at 4 29 53 PM" src="https://user-images.githubusercontent.com/7025236/182241990-5c3ac468-0d74-4117-8875-14a8da0b8e1f.png">

**Comment by alexkrechik** [comment]
Hi! I'm working on some comparatively big release 2.16.0 finishing - planning to release it in the nearest time.

**Comment by alexkrechik** [comment]
This issue is to be fixed or implemented in the 3.0.0 version of the extension. If this issue is unresolved or there are additional notes, please create a new ticket with the necessary details.
