### ISSUE TITLE
Unable to install on vscode

### ISSUE THREAD

**Issue by jefrinshaji** [alexkrechik/VSCucumberAutoComplete#458]
Unable to install on vscode (Windows 11).

**To Reproduce**
1. Go to 'https://marketplace.visualstudio.com/items?itemName=alexkrechik.cucumberautocomplete'
2. Click on 'Install'
4. See error (doesn't alert to open with vscode)

**Expected behavior**
Give an alert to open with vscode.

**Cucumberautocomplete part of VSCode settings:**
```
{
  "cucumberautocomplete.steps": [
      "features/step_definitions/*.js",
      "node_modules/@revjet/csp-qa/src/steps/*.js"
  ],
  "cucumberautocomplete.skipDocStringsFormat": true,
  "cucumberautocomplete.syncfeatures": "features/*.feature",
  "cucumberautocomplete.strictGherkinCompletion": true,
  "cucumberautocomplete.smartSnippets": true,
  "cucumberautocomplete.stepsInvariants": true,
  "cucumberautocomplete.onTypeFormat": false,
  "cucumberautocomplete.formatConfOverride": {
      "And": 0,
  }
}
```

**Step definition:**
If applicable, add example of step definition:
```
When(/^I rename the run to "([^"]*)"$/, (name) =>
  // ... whatever
);
```

**Gherkin step line**
If applicable, add step line from gherkin file
`When I rename the run to "([^"]*)"`

**Comment by alexkrechik** [comment]
Unfortunately, install extension functionality is out of this extension responsibility scope.
