### ISSUE TITLE
Show all steps rexeps with "|" as separate step

### ISSUE THREAD

**Issue by alexkrechik** [alexkrechik/VSCucumberAutoComplete#47]

**Comment by tiagolr** [comment]
Just showing the steps accepting the (|) would be great already (or not show an error an line on the feature doc), this is the only error I get so far, great extension.

**Comment by alexkrechik** [comment]
Unfortunately, we can't ignore such errors due to we should mark all the steps that are not accepted by cucumber.

**Comment by tiagolr** [comment]
But these are steps I'm using with cucumberjs, at least the version I'm using supports it.

**Comment by alexkrechik** [comment]
Could you please provide an example (step in js style and step in cucumber file) to be sure that we are about the same things ?

**Comment by tiagolr** [comment]
```js
this.Then(/^I (un)?(reject|allocate) "([^"]*)" opportunity card$/, (neg, type, target) => { ... }
this.Then(/^"([^"]*)"(?: checkbox|radio) is (not )?selected$/
this.Given(/^I select (network|brand|option|opportunity) "([^"]*)" on "([^"]*)"(?: selector)?$/, (type, name, target) => { ....}
 ```

These are the sort of steps that I'm working with that the extension does not recognize.
Thank you.

**Comment by alexkrechik** [comment]
Hi!
Not sure, that your issues are related to the "|" symbol. Example:

```
this.Then(
    /^(all |some )?"([^"]*)" text (does not )?contains?:?(?: "([^"]*)")?$/,
    (qtt, target, neg, value, table) => {
```

Step is not recognised, because page objects parsers looking for the any gherking word (like Then), and, after this, looking for the something like page-object ("", //, '') in this line to support multi-language parsing.

Try 
```
this.Then(/^(all |some )?"([^"]*)" text (does not )?contains?:?(?: "([^"]*)")?$/,
    (qtt, target, neg, value, table) => {
```
And your gherkin string app will looks good. Actually, this is the fastest fix you can use.

Also, in case of some issues left, please provide definition/usage in format **definition** + **warning string**  for each "step not found" error type to give me an ability to investigate this. 

Example:
`this.when(/^regexp$/) `- definition
`When regexp` - string was marked with error

**Comment by tiagolr** [comment]
Wow, not sure why someone re-indented the code like that but now its working great, no issues, thanks!
