### ISSUE TITLE
Unable to parse some step definitions from feature files

### ISSUE THREAD

**Issue by hcahsuchit** [alexkrechik/VSCucumberAutoComplete#49]
Like :"Given a patient exists
    And specialist type exists"

settings.json
{
    "cucumberautocomplete.steps": [
        "features/step_definitions/**/*.rb"
    ]
}

**Comment by alexkrechik** [comment]
Could you please provide  'Given a patient exists' step declaring.

Example:
When /^I select "([^"]*)" aspect as well$/ do |aspect_name|
  within('#aspects_list') do
    click_link aspect_name
  end
  step %Q(I should see "#{aspect_name}" aspect selected)
end

And please provide path to the file, where current declaration exists

Example - features/step_definitions/steps.rb

**Comment by hcahsuchit** [comment]
And (/^a patient exists$/) do
  @patient = FactoryGirl.build(:domestic_patient, backoffice: {rel: 'backoffice', href: @delhi_office.self_href}).save
  @patient.should be_valid
  @account_no = @patient.account_no
end

Path: features/step_definitions/back_office_user_journeys_steps.rb

**Comment by alexkrechik** [comment]
Fixed in 2.0.1 - please review
