### ISSUE TITLE
Version 3.0.0 ignores cucumberautocomplete.formatConfOverride

### ISSUE THREAD

**Issue by pct-cclausen** [alexkrechik/VSCucumberAutoComplete#491]
**Describe the bug**
Today I saved a feature-file and suddenly the formatting was broken.
Seems this is because 3.0.0 of the extension was autmoatically installed and it ignores my settings:

```
        "cucumberautocomplete.formatConfOverride": {
          "Funktionalität": 0,
          "Regel": 0,
          "Szenario": 1,
          "Angenommen": 2,
          "Wenn": 2,
          "Dann": 2,
          "Und": 2,
          "Aber": 2
        },
```

This causes the file to lose all indentation on format, breaking the file.

Switching back to the version 2.X.X fixes the issue for now.

**Step definition:**
Any german cucumber file such as:
```
    Szenario: S10 Offline kein Login
        Angenommen Helmut ist ein bereits registrierter Nutzer
        Und Helmut öffnet die Loginseite
        Wenn Helmut offline ist
        Dann ist dort ein Hinweis auf die fehlende Internetverbindung
```

This is in a devcontainer.

**Comment by alexkrechik** [comment]
Thanks for finding it, I will fix it soon.

**Comment by alexkrechik** [comment]
Hotfixed in 3.0.1 version of the extension

**Comment by pct-cclausen** [comment]
Wow that was fast
