### ISSUE TITLE
Unable to find the path of step definition file while navigating from steps in feature file (Ctrl + Click navigtes to File not found)

### ISSUE THREAD

**Issue by Janardan256** [alexkrechik/VSCucumberAutoComplete#497]
**Screenshots**
![image](https://github.com/alexkrechik/VSCucumberAutoComplete/assets/152237027/6755d686-cec7-4841-883e-83246cd41bfd)

**Comment by Janardan256** [comment]
@alexkrechik - Can you please have a look at this and let me know if you would require more details?

**Comment by gaomengsuijia** [comment]
me too

**Comment by alisher-qa** [comment]
3.0.2 path breakage seems to be specific for Windows. Didn't change on Linux.

**Comment by iskren-velichkov** [comment]
I have the same issue, too.
I am using Windows PC and my framework is Cypress with typescript and Cucumber

**Comment by alexkrechik** [comment]
Trying to solve a problem now.
Could anybody check please - if installing the 3.0.2 version back after 3.0.1 will the issue be reproduced again?

**Comment by purnay** [comment]
> Trying to solve a problem now. Could anybody check please - if installing the 3.0.2 version back after 3.0.1 will the issue be reproduced again?

Yes, I have installed back 3.0.2 after downgrading to 3.0.1 and the issue is back again on Windows 10

**Comment by hoangthanhtri** [comment]
The same issue even upgrade to 3.0.3
![image](https://github.com/alexkrechik/VSCucumberAutoComplete/assets/68146773/78035ec9-f0c8-43fe-b6e0-00b0119a6851)

**Comment by gaomengsuijia** [comment]
> The same issue even upgraded to 3.0.3 on VSCode IDE ![image](https://private-user-images.githubusercontent.com/68146773/337045787-78035ec9-f0c8-43fe-b6e0-00b0119a6851.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MzcwNDIsIm5iZiI6MTcxNzYzNjc0MiwicGF0aCI6Ii82ODE0Njc3My8zMzcwNDU3ODctNzgwMzVlYzktZjBjOC00M2ZlLWI2ZTAtMDBiMDExOWE2ODUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAxMTkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYTUzZjE5MWRkYTk4NjQ5MWU1MTAzYTA5ZmRmM2NmYTMyZmQ1MDNjY2Q3OWYzZTE5YzRjNzRhMzdlMjhmNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sqoVFWr0ZYk0jVL5QODj8lm1inAj4HmOw7hxd0Vrzv8)

+1

**Comment by lacell75** [comment]
same issue in my side

**Comment by alexkrechik** [comment]
Thanks, everybody, for the feedback, this issue is not reproducible in the dev mode, unfortunately, which makes its investigation more complicated, but I'm trying to fix it ASAP.

**Comment by Mathus** [comment]
We are having the same issue,
VS Code 1.90.0.
Cucumber (gherkin) Full Support v3.0.3
Window 11.

**Comment by innkush** [comment]
Same issue 
VS Code 1.90.0
Cucumber (gherkin) Full Support v3.0.3
Window 10

**Comment by iskren-velichkov** [comment]
I downgraded to v2.15.2 and also managed to work around the issue
![image](https://github.com/alexkrechik/VSCucumberAutoComplete/assets/16371203/3f7f82d6-83d6-4e16-8a69-39352aa74ef3)

**Comment by alexkrechik** [comment]
@romulodgomes  yes, thank you, I think you are right - path should be absolute, I am working on it now.

**Comment by alexkrechik** [comment]
Was it fixed for everybody in 3.0.5?

**Comment by lacell75** [comment]
I confirm. It fixed
