### ISSUE TITLE
Ctrl + Click navigtes to File not found

### ISSUE THREAD

**Issue by karl0ss** [alexkrechik/VSCucumberAutoComplete#498]
**Describe the bug**
CTRL + Click on step doesn't take to defintion any more, shows a "file not found page", but right clicking and selecint Got to definition works

Have just downgraded back to 3.0.1 from 3.0.2 and its working correctly again.

**To Reproduce**

- Ctrl + Click on a step in a feature file
- Definition is not displyed

**Expected behavior**
Step defintion should be displayed

**Screenshots**
N/A

**Cucumberautocomplete part of VSCode settings:**
```
{
  "cucumberautocomplete.steps": [
        "./features/steps/*.py"
    ],
    "cucumberautocomplete.customParameters": [
        {
            "parameter": "(u'",
            "value": "('"
        },
        {
            "parameter": "(\nu'",
            "value": "('"
        }
    ],
    "cucumberautocomplete.syncfeatures": "./features/*",
    "cucumberautocomplete.gherkinDefinitionPart": "@(given|when|then|step)\\(",
    "cucumberautocomplete.strictGherkinCompletion": false,
    "cucumberautocomplete.strictGherkinValidation": false,
    "cucumberautocomplete.onTypeFormat": true,
}
```

**Comment by purnay** [comment]
Exactly same issue for me as well. I had to downgrade to 3.0.1
New version is unable to navigate to steps files.
