### ISSUE TITLE
Steps implementation path can not be opened

### ISSUE THREAD

**Issue by screek8000** [alexkrechik/VSCucumberAutoComplete#57]
Hi,

I am trying to use your extension and configured the cucumberautocomplete.steps in settings.json.
Now when pressing F12 to go to the steps implementation the search seems to be successful, but the path can not be openend.

I get an error message fromVS Code, e.g.: 
General.steps.js kann nicht geöffnet werden: Die Datei wurde nicht gefunden (\\c:\Solutions\Dev\Source_Develop\Tests\Selenium\src\Steps\General.steps.js).

Sorry for german error message, but I think the Problem is the "\\" at the beginning of the path.

My settings.json:
`{
    "cucumberautocomplete.steps": [
        "src/Steps/*.js"
    ],
    "cucumberautocomplete.pages": {
    }
}`

I am using version 2.0.1 of Cucumber Autocomplete Extension with Visual Studio Code 1.11.1 (Windows 7).

Thanks and regards

**Comment by alexkrechik** [comment]
Should be fixed in 2.1.0 version of plugin

**Comment by screek8000** [comment]
Works great now, thank you
