### ISSUE TITLE
Go to Definition throws error File not found with wrong path

### ISSUE THREAD

**Issue by dubbya** [alexkrechik/VSCucumberAutoComplete#62]
When clicking Go to Definition this error shows:

**Unable to open 'step_defs.js': File not found (\\c:\leave\features\support\step_defs.js).** Problem looks to be the \\c:\.

My settings.json is this and using 2.0.1 in 1.11.2 of vscode:

{
    "cucumberautocomplete.steps": [
        "features/support/*.js"
    ],
    "cucumberautocomplete.pages": {
    },
    "editor.quickSuggestions": {
        "comments": true,
        "strings": true,
        "other": true
    }
}

**Comment by alexkrechik** [comment]
Should be fixed in 2.1.0 version of plugin
