### ISSUE TITLE
Highlighting as a comment when the # is after text

### ISSUE THREAD

**Issue by baderbuddy** [alexkrechik/VSCucumberAutoComplete#63]
The syntax highlighting is showing the following as a comment.

`Given some precondition #Hello`

When Cucumber should only recognize it as a comment if the `#` is at the start of the line or only has white space.

**Comment by alexkrechik** [comment]
All the comments are handling by VSCode, not by extension itself. Unfortunately, there are no ability to set any comments restriction, we can only provide "lineComment" an "blockComment" symbols, that will be used by VSCode to determine comments.

**Comment by baderbuddy** [comment]
There is a fix possible, it's just changing the syntax file.
https://github.com/alexkrechik/VSCucumberAutoComplete/pull/75

**Comment by alexkrechik** [comment]
Its really works, thank you.

**Comment by baderbuddy** [comment]
No problem, all I ask is a statue made in u honor.

I'm joking. Thanks for accepting the pull :)
