### ISSUE TITLE
Cannot work with some build-in/custom parameter types

### ISSUE THREAD

**Issue by duyphuong13** [alexkrechik/VSCucumberAutoComplete#66]
Extension doesn't work with some  build-in and custom parameter types like : "float", "int" or "stringInDoubleQuotes" of Cucumber 2
`When('I type {stringInDoubleQuotes} into textbox {stringInDoubleQuotes}', function (value, name, next) {})`

https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/api_reference.md

**Comment by alexkrechik** [comment]
Realized in 2.2.0
