### ISSUE TITLE
Add snippets for support JS files like World, Hooks

### ISSUE THREAD

**Issue by lashchev** [alexkrechik/VSCucumberAutoComplete#80]
Also add snippets that explain access to custom properties defined in World

**Comment by alexkrechik** [comment]
Could you please provide a snippet example ?

**Comment by alexkrechik** [comment]
Snippets are looks like (for Then gherkin step):
"prefix": "Then",
        "body": [
            "Then ${Start to type your Then step here}"
        ]
Where body will be changed with 'Then' step body.

Could you please reopen issue with snippet exampl or additional info regarding implementation required?

Thank you.

**Comment by lashchev** [comment]
Here is a sample of world.js that I use (don't have hooks.js handy):
'use strict';
const { defineSupportCode } = require('cucumber');

function WorldConstructor({ attach, parameters }) {
    this.attach = attach;
    this.parameters = parameters;
    this.myCustomWorldProperty = "some initial value";
}

defineSupportCode(function ({ setWorldConstructor }) {
    setWorldConstructor(WorldConstructor);
});

**Comment by lashchev** [comment]
Good snippet for hooks.js can be found here: https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md

**Comment by lashchev** [comment]
Implementation wise it would be nice to add file and/or editor context menu options "Add world.js" and "Add hooks.js" that would create selected file in the "support" folder with the given snippets.

**Comment by alexkrechik** [comment]
Unfortunately, extension handle only cucumber language, so should insert snippets to the .feature files only. Also, this extension handling all the gherkin files without binding to the some programming language (it should work for any language (Java, JS, Ruby, etc) and cucumber implementation).
I can reopen current issue, but, looks like, such functional should not be realized in this extension scope.

**Comment by lashchev** [comment]
Got it.

Since it already understands JS step definitions I thought it would be nice to have this as a general cucumber VSCode framework supporting different languages, but then realized that the name of the extension explicitly defines the scope - only to autocomplete....

Not much cucumber tools for VSCode so far and I hoped this one to save the day :-)
