### ISSUE TITLE
Add global pattern support for cucumberautocomplete.steps and cucumberautocomplete.pages

### ISSUE THREAD

**Issue by Marketionist** [alexkrechik/VSCucumberAutoComplete#81]
Please add global pattern support for `cucumberautocomplete.steps` and `cucumberautocomplete.pages` in `settings.json`.

Would be great to use something like:
```
...
"cucumberautocomplete.steps": [
        "*/test/features/step_definitions/**/*.js"
    ],
    "cucumberautocomplete.pages": {
        "users": "*/test/features/support/page_objects/**/*.js",
    },
...
```
for multiple apps with the same structure that are placed in one folder.

**Comment by alexkrechik** [comment]
Should be fixed in 2.3.0
