### ISSUE TITLE
Remove duplicated entries if they happen in cucumberautocomplete.steps and cucumberautocomplete.pages in settings.json

### ISSUE THREAD

**Issue by Marketionist** [alexkrechik/VSCucumberAutoComplete#82]
Please remove duplicated entries if they happen in `cucumberautocomplete.steps` and `cucumberautocomplete.pages` for multiple apps with the same structure that are placed in one folder.

<img width="677" alt="duplicates" src="https://cloud.githubusercontent.com/assets/534603/26552703/f0c71466-4490-11e7-9b31-8e5d313a7325.png">

**Comment by Marketionist** [comment]
Please note that this issue is connected to https://github.com/alexkrechik/VSCucumberAutoComplete/issues/81

**Comment by alexkrechik** [comment]
Should be fixed in 2.3.0
