### ISSUE TITLE
Add possibility to specify paths to features inside cucumberautocomplete.syncfeatures

### ISSUE THREAD

**Issue by Marketionist** [alexkrechik/VSCucumberAutoComplete#83]
Please add possibility to specify paths to features inside `cucumberautocomplete.syncfeatures` in `settings.json`.

Would be great to have 3 possible configs for `cucumberautocomplete.syncfeatures`:
- `true` - parse all features
- `false` - don't parse any features
- `["path/to/feature1/**/*.js", "path/to/feature2/**/*.js"]` - parse only specified features

**Comment by alexkrechik** [comment]
Should be fixed in 2.3.0
