### ISSUE TITLE
Change identation from 4 spaces to 2 spaces

### ISSUE THREAD

**Issue by lashchev** [alexkrechik/VSCucumberAutoComplete#88]
Like in https://cucumber.io/docs/reference

**Comment by alexkrechik** [comment]
Extension using VSCode editor indentation settings, so u can use any settings u need via changing them in the editor - 
![screen shot](https://cloud.githubusercontent.com/assets/5772406/26822643/70d0ff5a-4ab3-11e7-857e-e26647b717a3.png)

**Comment by lashchev** [comment]
Thanks! Didn't realize this because VSC typically ignores this setting with editor.detectIndentation=true
Is it possible to match VSC behavior for feature files formatting? I mean use VSC to detect indentation and use detected indentation instead of the global one?

**Comment by alexkrechik** [comment]
It looks like unreal - we can't detect tabsize (it would be just '\t' in code), and, in case of different num of spaces for the same strings, we cant determine how many spaces are actualy needs.

**Comment by alexkrechik** [comment]
Closed due to autodetection works now.
